import path from 'node:path';

import { getAdapter } from '../registry/adapters.js';
import { getComponentEntry } from '../registry/components.js';
import { writeTextFile } from '../utils/fs.js';
import type { ConfigPaths, CliConfig } from '../config/project-config.js';
import type { ComponentPreset } from '../registry/components.js';

function createFileHeader(): string[] {
  return ['/* This file is auto-generated by @proto.ui/cli. */', '/* Do not edit by hand. */', ''];
}

function groupImports(componentIds: string[]): Map<string, Set<string>> {
  const importPaths = new Map<string, Set<string>>();

  for (const componentId of componentIds) {
    const entry = getComponentEntry(componentId);
    if (!entry) continue;
    const set = importPaths.get(entry.importPath) ?? new Set<string>();
    for (const item of entry.items) set.add(item.prototypeImport);
    importPaths.set(entry.importPath, set);
  }

  return importPaths;
}

function renderPreset(host: string, preset: ComponentPreset): string[] {
  const {
    exportName,
    rootExport,
    defaultPartExport,
    defaultPartElementName,
    inputName,
    elementName,
    omissionAttribute,
  } = preset;

  if (host === 'react') {
    return [
      `export type ${exportName}Props = Omit<React.ComponentProps<typeof ${rootExport}>, 'children'> & {`,
      `  children?: React.ReactNode;`,
      `  ${inputName}?: React.ReactElement<React.ComponentProps<typeof ${defaultPartExport}>, typeof ${defaultPartExport}> | null;`,
      `};`,
      `export const ${exportName} = React.forwardRef<React.ComponentRef<typeof ${rootExport}>, ${exportName}Props>(`,
      `  ({ ${inputName}, children, ...props }, ref) => {`,
      `    const childList = React.Children.toArray(children);`,
      `    const hasDirectDefaultPart = childList.some(`,
      `      (child) => React.isValidElement(child) && child.type === ${defaultPartExport}`,
      `    );`,
      `    const resolvedDefaultPart =`,
      `      ${inputName} === null || hasDirectDefaultPart`,
      `        ? null`,
      `        : ${inputName} ?? React.createElement(${defaultPartExport});`,
      `    const rootProps = ref == null ? props : { ...props, ref };`,
      `    return React.createElement(${rootExport}, rootProps, children, resolvedDefaultPart);`,
      `  }`,
      `);`,
      `${exportName}.displayName = '${exportName}';`,
    ];
  }

  if (host === 'vue') {
    return [
      `export const ${exportName} = Vue.defineComponent({`,
      `  name: '${exportName}',`,
      `  inheritAttrs: false,`,
      `  setup(_props, { attrs, slots, expose }) {`,
      `    const root = Vue.ref<any>(null);`,
      `    expose({`,
      `      update: () => root.value?.update?.(),`,
      `      getExposes: () => root.value?.getExposes?.() ?? {},`,
      `      invokeInCallbackScope: (fn: () => void) => root.value?.invokeInCallbackScope?.(fn),`,
      `    });`,
      `    return () => {`,
      `      const children = slots.default?.() ?? [];`,
      `      const hasDirectDefaultPart = children.some((child) => child.type === ${defaultPartExport});`,
      `      const resolvedDefaultPart = slots.${inputName}`,
      `        ? slots.${inputName}!()`,
      `        : hasDirectDefaultPart`,
      `          ? []`,
      `          : [Vue.h(${defaultPartExport})];`,
      `      return Vue.h(${rootExport}, { ...attrs, ref: root }, [...children, ...resolvedDefaultPart]);`,
      `    };`,
      `  },`,
      `});`,
    ];
  }

  if (host === 'vue2') {
    return [
      `export const ${exportName} = {`,
      `  name: '${exportName}',`,
      `  inheritAttrs: false,`,
      `  methods: {`,
      `    update(this: any) {`,
      `      this.$refs.root?.update?.();`,
      `    },`,
      `    getExposes(this: any) {`,
      `      return this.$refs.root?.getExposes?.() ?? {};`,
      `    },`,
      `    invokeInCallbackScope(this: any, fn: () => void) {`,
      `      this.$refs.root?.invokeInCallbackScope?.(fn);`,
      `    },`,
      `  },`,
      `  render(this: any, h: any) {`,
      `    const children = this.$slots.default ?? [];`,
      `    const hasDirectDefaultPart = children.some(`,
      `      (child: any) => child.componentOptions?.Ctor === ${defaultPartExport}`,
      `    );`,
      `    const namedDefaultPart = this.$scopedSlots?.${inputName}?.() ?? this.$slots.${inputName};`,
      `    const resolvedDefaultPart = namedDefaultPart`,
      `      ? namedDefaultPart`,
      `      : hasDirectDefaultPart`,
      `        ? []`,
      `        : [h(${defaultPartExport})];`,
      `    return h(${rootExport}, {`,
      `      ref: 'root',`,
      `      attrs: this.$attrs,`,
      `      on: this.$listeners,`,
      `    }, [...children, ...resolvedDefaultPart]);`,
      `  },`,
      `};`,
    ];
  }

  return [
    `export class ${exportName}Element extends ${rootExport}Element {`,
    `  connectedCallback() {`,
    `    const hasDirectDefaultPart = Array.from(this.children).some(`,
    `      (child) => child.localName === '${defaultPartElementName}'`,
    `    );`,
    `    ((${rootExport}Element.prototype as unknown) as { connectedCallback?: () => void }).connectedCallback?.call(this);`,
    `    if (!hasDirectDefaultPart && !this.hasAttribute('${omissionAttribute}')) {`,
    `      this.append(document.createElement('${defaultPartElementName}'));`,
    `    }`,
    `  }`,
    `}`,
    `if (!customElements.get('${elementName}')) {`,
    `  customElements.define('${elementName}', ${exportName}Element);`,
    `}`,
  ];
}

export function renderHostIndex(host: string, componentIds: string[]): string {
  const adapter = getAdapter(host);
  if (!adapter) throw new Error(`unsupported host "${host}"`);

  const lines = createFileHeader();
  if (componentIds.length === 0) {
    lines.push('export {};', '');
    return lines.join('\n');
  }

  lines.push(adapter.createImport);
  if (adapter.runtimeImport) lines.push(adapter.runtimeImport);

  const grouped = groupImports(componentIds);
  for (const [importPath, imports] of grouped) {
    lines.push(`import { ${Array.from(imports).sort().join(', ')} } from '${importPath}';`);
  }

  lines.push('');
  if (adapter.adapterStatement) {
    lines.push(adapter.adapterStatement);
    lines.push('');
  }

  for (const componentId of componentIds) {
    const entry = getComponentEntry(componentId);
    if (!entry) continue;

    for (const item of entry.items) {
      if (host === 'react') {
        lines.push(`export const ${item.reactExport} = adapt(${item.prototypeImport});`);
      } else if (host === 'vue' || host === 'vue2') {
        lines.push(`export const ${item.vueExport} = adapt(${item.prototypeImport});`);
      } else if (host === 'wc') {
        lines.push(
          `export const ${item.wcExport} = AdaptToWebComponent(${item.prototypeImport}, { registerAs: '${item.elementName}' });`
        );
      }
    }
    if (entry.preset) lines.push(...renderPreset(host, entry.preset));
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

export function renderRootIndex(componentsByHost: Record<string, string[]>): string {
  const lines = createFileHeader();
  let wrote = false;

  for (const host of Object.keys(componentsByHost).sort()) {
    const adapter = getAdapter(host);
    if (!adapter) {
      throw new Error(`unsupported host "${host}" in Proto UI config`);
    }
    const componentIds = componentsByHost[host] ?? [];

    for (const componentId of componentIds) {
      const entry = getComponentEntry(componentId);
      if (!entry) continue;

      for (const item of entry.items) {
        if (host === 'wc') {
          lines.push(`export { ${item.wcExport} } from './wc';`);
          wrote = true;
          continue;
        }

        const exportName = host === 'react' ? item.reactExport : item.vueExport;
        lines.push(
          `export { ${exportName} as ${adapter.rootAliasPrefix}${exportName} } from './${host}';`
        );
        wrote = true;
      }
      if (entry.preset) {
        const exportName =
          host === 'wc' ? `${entry.preset.exportName}Element` : entry.preset.exportName;
        if (host === 'wc') {
          lines.push(`export { ${exportName} } from './wc';`);
        } else {
          lines.push(
            `export { ${exportName} as ${adapter.rootAliasPrefix}${exportName} } from './${host}';`
          );
        }
        wrote = true;
      }
    }
  }

  if (!wrote) lines.push('export {};');
  lines.push('');
  return lines.join('\n');
}

export async function writeGeneratedIndexes(paths: ConfigPaths, config: CliConfig): Promise<void> {
  const componentsByHost = config.components ?? {};
  for (const host of Object.keys(componentsByHost)) {
    const componentIds = componentsByHost[host] ?? [];
    const hostFile = path.join(paths.componentsDir, host, 'index.ts');
    await writeTextFile(hostFile, renderHostIndex(host, componentIds));
  }

  await writeTextFile(
    path.join(paths.componentsDir, 'index.ts'),
    renderRootIndex(componentsByHost)
  );
}
