import {
  PROTO_SHADOW_STYLE_ARTIFACT_KIND,
  PROTO_SHADOW_STYLE_ARTIFACT_VERSION,
  PROTO_SHADOW_STYLE_ENVIRONMENT,
  renderProtoShadowSplitStyleArtifact,
  renderProtoStyleTokenCss,
  type ShadowStyleTokenUsage,
} from './proto-style-css';

/** Internal serializer shared by F1 CLI delivery and controlled consumer fixtures.
 * No package-root builder export; the CLI fixes its generated export name. */
export function renderShadowStyleDelivery(
  tokens: readonly string[],
  exportName: string,
  usage?: ShadowStyleTokenUsage
) {
  if (!/^[A-Za-z_$][\w$]*$/.test(exportName) || exportName === 'default') {
    throw new Error('[shadow delivery] expected a named JavaScript export identifier');
  }
  const closure = [...tokens];
  const artifact = renderProtoShadowSplitStyleArtifact(closure, usage);
  const literal = JSON.stringify(artifact)
    .replaceAll('<', '\\u003c')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
  return Object.freeze({
    documentCss: renderProtoStyleTokenCss(closure),
    shadowModule: [
      '// Generated by Proto UI. Do not edit; no DOM or runtime renderer dependency.',
      `const artifact = Object.freeze(${literal});`,
      `export { artifact as ${exportName} };`,
      '',
    ].join('\n'),
    shadowDeclaration: [
      '// Generated by Proto UI. Regenerate with the JavaScript companion.',
      `declare const artifact: Readonly<{`,
      `  kind: ${JSON.stringify(PROTO_SHADOW_STYLE_ARTIFACT_KIND)};`,
      `  version: ${PROTO_SHADOW_STYLE_ARTIFACT_VERSION};`,
      `  environment: ${JSON.stringify(PROTO_SHADOW_STYLE_ENVIRONMENT)};`,
      '  cssText: string;',
      '}>;',
      `export { artifact as ${exportName} };`,
      '',
    ].join('\n'),
  });
}
