/**
 * Emits the protocol message fixture that the Rust envelopes round-trip.
 *
 * The TypeScript envelopes in `packages/host-protocol/src/messages.ts` are
 * types, with nothing to run. So the recorded artifact is a set of examples
 * the compiler has checked against those types
 * (`packages/host-protocol/test/message-examples.ts`, keyed by `kind` so a
 * kind cannot be added or removed without the examples following). The Rust
 * side deserializes each example into its envelope and serializes it back,
 * and must reproduce it exactly: no field dropped, no field invented.
 *
 *   pnpm gpui:message-fixture            # write
 *   pnpm check:gpui-message-fixture      # verify it is current
 *
 * `--fixture <path>` targets a different file, which lets a test prove that a
 * stale fixture actually fails the check instead of asserting that it would.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  HOST_TO_PEER_EXAMPLES,
  PEER_TO_HOST_EXAMPLES,
} from '../../packages/host-protocol/test/message-examples';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const DEFAULT_OUT = path.join(ROOT, 'native/gpui/fixtures/protocol-messages.json');

function optionPath(argv: readonly string[], flag: string, fallback: string): string {
  const at = argv.indexOf(flag);
  if (at === -1) return fallback;
  const value = argv[at + 1];
  if (!value) throw new Error(`${flag} needs a path`);
  return path.resolve(ROOT, value);
}

function compare(label: string, target: string, expected: string): boolean {
  let actual: string;
  try {
    actual = readFileSync(target, 'utf8');
  } catch {
    console.error(`[gpui:message-fixture] ${path.relative(ROOT, target)} is missing`);
    return false;
  }
  if (actual === expected) {
    console.log(`[gpui:message-fixture] ${path.relative(ROOT, target)} is current (${label})`);
    return true;
  }
  console.error(
    `[gpui:message-fixture] ${path.relative(ROOT, target)} is stale; run \`pnpm gpui:message-fixture\``
  );
  return false;
}

export function main(argv: readonly string[] = process.argv.slice(2)): void {
  const hostToPeer = Object.values(HOST_TO_PEER_EXAMPLES).flat();
  const peerToHost = Object.values(PEER_TO_HOST_EXAMPLES).flat();
  const fixture = {
    note:
      'Generated by scripts/gpui/generate-message-fixture.mts from compiler-checked ' +
      'examples of every message kind. Do not edit.',
    source: 'packages/host-protocol/test/message-examples.ts',
    /** Every kind in each direction, whether or not a later example repeats it. */
    kinds: {
      hostToPeer: Object.keys(HOST_TO_PEER_EXAMPLES),
      peerToHost: Object.keys(PEER_TO_HOST_EXAMPLES),
    },
    hostToPeer,
    peerToHost,
  };

  const serialized = `${JSON.stringify(fixture, null, 2)}\n`;
  const out = optionPath(argv, '--fixture', DEFAULT_OUT);
  const label =
    `${fixture.kinds.hostToPeer.length} host-to-peer and ` +
    `${fixture.kinds.peerToHost.length} peer-to-host kinds, ` +
    `${hostToPeer.length + peerToHost.length} examples`;

  if (argv.includes('--check')) {
    if (!compare(label, out, serialized)) process.exitCode = 1;
    return;
  }
  writeFileSync(out, serialized);
  console.log(`[gpui:message-fixture] wrote ${path.relative(ROOT, out)}: ${label}`);
}

// Only run when executed directly; a test imports `main` instead.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
