/**
 * Records what the real GPUI peer sends for a Base Button session, for the
 * Rust host to render and replay.
 *
 * The session runs `createPeerSession` from `packages/adapters/gpui-peer`
 * against `@proto.ui/prototypes-base/button`, with a minimal host that
 * applies every projection. Nothing here restates what a Button projects: the
 * template, the event registrations, the focus plan and the accessibility
 * snapshot are whatever the peer produced.
 *
 *   pnpm gpui:button-session-fixture            # write
 *   pnpm check:gpui-button-session-fixture      # verify it is current
 *
 * `--fixture <path>` targets a different file, which lets a test prove that a
 * stale fixture actually fails the check instead of asserting that it would.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import button from '@proto.ui/prototypes-base/button';
import type { PeerToHostMessage, WireRecord } from '@proto.ui/host-protocol';

import { createPeerSession } from '../../packages/adapters/gpui-peer/src/session';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const DEFAULT_OUT = path.join(ROOT, 'native/gpui/fixtures/base-button-session.json');

/** The surface the peer waits for before it treats its focus target as ready. */
const READY_SURFACE = 'proto-surface';

/** Runs one session to its first activation and returns everything the peer sent. */
async function record(sessionId: string, props: WireRecord): Promise<PeerToHostMessage[]> {
  const sent: PeerToHostMessage[] = [];
  const pending: Array<() => void> = [];
  const peer = createPeerSession({
    sessionId,
    instanceId: `${sessionId}:instance`,
    prototype: button,
    props,
    send: (message) => {
      sent.push(message);
      if (message.kind !== 'projection.install') return;
      const { transaction } = message;
      // Acknowledge after the install returns, as a host across a transport would.
      pending.push(() =>
        peer.handle({
          kind: 'projection.ack',
          ack: {
            sessionId: transaction.sessionId,
            viewEpoch: transaction.viewEpoch,
            commitId: transaction.commitId,
            status: 'applied',
            readySurfaces: [READY_SURFACE],
            diagnostics: [],
          },
        })
      );
    },
    schedule: (task) => task(),
  });
  await peer.mount();
  while (pending.length > 0) pending.shift()!();
  return sent;
}

function optionPath(argv: readonly string[], flag: string, fallback: string): string {
  const at = argv.indexOf(flag);
  if (at === -1) return fallback;
  const value = argv[at + 1];
  if (!value) throw new Error(`${flag} needs a path`);
  return path.resolve(ROOT, value);
}

function compare(label: string, target: string, expected: string): boolean {
  let actual: string;
  try {
    actual = readFileSync(target, 'utf8');
  } catch {
    console.error(`[gpui:button-session-fixture] ${path.relative(ROOT, target)} is missing`);
    return false;
  }
  if (actual === expected) {
    console.log(
      `[gpui:button-session-fixture] ${path.relative(ROOT, target)} is current (${label})`
    );
    return true;
  }
  console.error(
    `[gpui:button-session-fixture] ${path.relative(ROOT, target)} is stale; ` +
      'run `pnpm gpui:button-session-fixture`'
  );
  return false;
}

export async function main(argv: readonly string[] = process.argv.slice(2)): Promise<void> {
  const sessions = {
    enabled: await record('button-enabled', {}),
    disabled: await record('button-disabled', { disabled: true }),
  };
  const fixture = {
    note:
      'Generated by scripts/gpui/generate-button-session-fixture.mts by running the real ' +
      'GPUI peer against Base Button. Do not edit.',
    prototype: '@proto.ui/prototypes-base/button',
    readySurface: READY_SURFACE,
    /** Every message the peer sent, in order, up to and including activation. */
    sessions,
  };

  const serialized = `${JSON.stringify(fixture, null, 2)}\n`;
  const out = optionPath(argv, '--fixture', DEFAULT_OUT);
  const label = Object.entries(sessions)
    .map(([name, messages]) => `${name}: ${messages.length} messages`)
    .join(', ');

  if (argv.includes('--check')) {
    if (!compare(label, out, serialized)) process.exitCode = 1;
    return;
  }
  writeFileSync(out, serialized);
  console.log(`[gpui:button-session-fixture] wrote ${path.relative(ROOT, out)}: ${label}`);
}

// Only run when executed directly; a test imports `main` instead.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
