// Table geometry is semantic; host cells are discovered by exact Anatomy family identity.
export const gpuiNativeTableSource = String.raw`
const TABLE_FAMILY_ID:&str="@proto.ui/module-table-structure#TABLE_STRUCTURE_FAMILY";
#[derive(Default)]
pub struct TableModule{pub role:String,pub config:BTreeMap<String,Value>,pub snapshot:Value}
#[derive(Clone)]
struct TableCell{owner:OwnerRef,row:usize,column:u64,row_span:u64,column_span:u64,kind:String,column_headers:Vec<Value>,row_headers:Vec<Value>,ordered_headers:Vec<Value>}
pub fn table_setup(owner:&OwnerWeak,role:Value)->Value{let role=role.text();assert!(["root","caption","row","headerCell","cell"].contains(&role.as_str()),"invalid table role");let owner_ref=setup(owner);let previous=owner_ref.borrow().modules.topology.table.role.clone();assert!(previous.is_empty()||previous==role,"table role already declared");if previous.is_empty(){for(key,name,kind,initial)in[("table.a11yRole","tableA11yRole","string",Value::string("")),("table.rowCount","tableRowCount","discrete",Value::number(0.)),("table.columnCount","tableColumnCount","discrete",Value::number(0.)),("table.row","tableRow","discrete",Value::number(-1.)),("table.column","tableColumn","discrete",Value::number(-1.)),("table.rowSpan","tableRowSpan","discrete",Value::number(0.)),("table.columnSpan","tableColumnSpan","discrete",Value::number(0.))]{let state=owned_state(owner,name,kind,initial);owner_ref.borrow_mut().modules.topology.handles.insert(key.into(),state);}owner_ref.borrow_mut().modules.topology.table.role=role;}module_handle(owner,"table-structure")}
pub fn table_configure(owner:&OwnerWeak,patch:Value)->Value{let owner=runtime(owner);merge_config(&mut owner.borrow_mut().modules.topology.table.config,patch);topology_refresh();Value::Undefined}
pub fn table_snapshot(owner:&OwnerWeak)->Value{let owner=ensure(owner);let snapshot=owner.borrow().modules.topology.table.snapshot.clone();if snapshot.nullish(){Value::Json(Json::Null)}else{snapshot}}
pub fn table_object_ref(owner:&OwnerWeak)->Value{ensure(owner);Value::ObjectRef(owner.clone())}
fn table_diagnostic(code:&str,owner:Option<&OwnerRef>,row:Option<usize>,key:Option<&str>)->Value{let mut fields=vec![("code",Value::string(code))];if let Some(owner)=owner{fields.push(("ref",Value::ObjectRef(Rc::downgrade(owner))))}if let Some(row)=row{fields.push(("row",Value::number(row as f64)))}if let Some(key)=key{fields.push(("headerKey",Value::string(key)))}record(fields)}
fn table_clear(owner:&OwnerRef){internal_state(owner,"table.a11yRole",Value::string(""));for key in ["table.rowCount","table.columnCount","table.row","table.column","table.rowSpan","table.columnSpan"]{internal_state(owner,key,Value::number(0.));}let mut o=owner.borrow_mut();o.modules.topology.table.snapshot=Value::Undefined;for key in ["columnHeaders","rowHeaders","caption","labelledBy"]{o.modules.accessible_relations.remove(key);}}
fn table_ref(owner:&OwnerRef)->Value{Value::ObjectRef(Rc::downgrade(owner))}
fn table_relation(owner:&OwnerRef,key:&str,targets:Vec<Value>){owner.borrow_mut().modules.accessible_relations.insert(key.into(),record(vec![("target",Value::Array(Rc::new(targets)))]));}
fn table_refresh(owners:&[OwnerRef]){
    for owner in owners{if !owner.borrow().modules.topology.table.role.is_empty(){table_clear(owner)}}
    for root in owners{
        if !ready(root)||root.borrow().modules.topology.table.role!="root"||!root.borrow().modules.topology.claims.get(TABLE_FAMILY_ID).is_some_and(|c|c.role=="root"){continue}
        let mut diagnostics=Vec::new();let domain=anatomy_members(root,TABLE_FAMILY_ID,None,false);let mut records=Vec::new();for owner in domain{let o=owner.borrow();let role=&o.modules.topology.table.role;if role.is_empty(){continue}if o.modules.topology.claims[TABLE_FAMILY_ID].role!=*role{diagnostics.push(table_diagnostic("role-mismatch",Some(&owner),None,None));}else{drop(o);records.push(owner);}}
        let captions:Vec<_>=records.iter().filter(|o|o.borrow().modules.topology.table.role=="caption").cloned().collect();let rows:Vec<_>=records.iter().filter(|o|o.borrow().modules.topology.table.role=="row").cloned().collect();if captions.len()>1{diagnostics.push(table_diagnostic("multiple-captions",None,None,None))}if rows.is_empty(){diagnostics.push(table_diagnostic("missing-row",None,None,None))}
        let mut row_cells:Vec<Vec<OwnerRef>>=vec![vec![];rows.len()];let mut headers=0;let mut normal=0;
        for owner in records.iter().filter(|o|["headerCell","cell"].contains(&o.borrow().modules.topology.table.role.as_str())){let mut parent=owner.borrow().parent.upgrade();let mut row=None;while let Some(p)=parent{if let Some(index)=rows.iter().position(|r|Rc::ptr_eq(r,&p)){row=Some(index);break}if Rc::ptr_eq(&p,root){break}parent=p.borrow().parent.upgrade();}if let Some(row)=row{row_cells[row].push(owner.clone());}else{diagnostics.push(table_diagnostic("missing-row-parent",Some(owner),None,None));}}
        let mut occupied:BTreeMap<usize,Vec<(u64,u64)>>=BTreeMap::new();let mut placed=Vec::<TableCell>::new();let mut column_count=0u64;let mut headers_by_key:BTreeMap<String,Vec<OwnerRef>>=BTreeMap::new();
        for(row,cells)in row_cells.iter().enumerate(){if cells.is_empty(){diagnostics.push(table_diagnostic("empty-row",Some(&rows[row]),Some(row),None));}let mut cursor=0u64;
            for owner in cells{let config=owner.borrow().modules.topology.table.config.clone();let header=owner.borrow().modules.topology.table.role=="headerCell";let header_key=text_or(field(&config,"headerKey"),"");let header_kind=text_or(field(&config,"headerKind"),"");if header{headers+=1;if header_key.is_empty(){diagnostics.push(table_diagnostic("missing-header-key",Some(owner),Some(row),None))}else{headers_by_key.entry(header_key).or_default().push(owner.clone());}if header_kind!="column"&&header_kind!="row"{diagnostics.push(table_diagnostic("missing-header-kind",Some(owner),Some(row),None));}}else{normal+=1;}
                let rs=field(&config,"rowSpan");let cs=field(&config,"columnSpan");let rs=if rs.nullish(){1.}else{rs.num()};let cs=if cs.nullish(){1.}else{cs.num()};if !rs.is_finite()||!cs.is_finite()||rs<1.||cs<1.||rs.fract()!=0.||cs.fract()!=0.||rs>9007199254740991.||cs>9007199254740991.{diagnostics.push(table_diagnostic("invalid-span",Some(owner),None,None));continue}let rs=rs as u64;let cs=cs as u64;if row as u64+rs>rows.len()as u64{diagnostics.push(table_diagnostic("row-span-out-of-range",Some(owner),Some(row),None));continue}
                let mut column=cursor;loop{if column+cs>9007199254740991{break}let mut next=column;for r in row..row+rs as usize{if let Some(intervals)=occupied.get(&r){for(start,end)in intervals{if *end>column&&*start<column+cs{next=next.max(*end);}}}}if next==column{break}column=next;}
                if column+cs>9007199254740991{diagnostics.push(table_diagnostic("column-range-out-of-range",Some(owner),Some(row),None));continue}for r in row..row+rs as usize{occupied.entry(r).or_default().push((column,column+cs));}cursor=column+cs;column_count=column_count.max(cursor);placed.push(TableCell{owner:owner.clone(),row,column,row_span:rs,column_span:cs,kind:if !header{"cell"}else if header_kind=="row"{"row-header"}else{"column-header"}.into(),column_headers:vec![],row_headers:vec![],ordered_headers:vec![]});
            }
        }
        if headers==0{diagnostics.push(table_diagnostic("missing-header-cell",None,None,None))}if normal==0{diagnostics.push(table_diagnostic("missing-cell",None,None,None))}for(key,matches)in &headers_by_key{if matches.len()>1{diagnostics.push(table_diagnostic("duplicate-header-key",matches.first(),None,Some(key)))}}
        for(row,cells)in row_cells.iter().enumerate(){for owner in cells{let config=owner.borrow().modules.topology.table.config.clone();let refs=field(&config,"headers");let refs=if refs.nullish(){vec![]}else{refs.items()};if refs.is_empty()&&owner.borrow().modules.topology.table.role=="cell"{diagnostics.push(table_diagnostic("missing-cell-headers",Some(owner),Some(row),None));}let source=placed.iter().position(|c|Rc::ptr_eq(&c.owner,owner));let mut seen=BTreeSet::new();for key in refs{let key=key.text();let error=if key.is_empty(){Some("empty-header-reference")}else if !seen.insert(key.clone()){Some("duplicate-header-reference")}else{None};if let Some(error)=error{diagnostics.push(table_diagnostic(error,Some(owner),Some(row),Some(&key)));continue}let Some(matches)=headers_by_key.get(&key)else{diagnostics.push(table_diagnostic("missing-header-target",Some(owner),Some(row),Some(&key)));continue};if matches.len()!=1{diagnostics.push(table_diagnostic("ambiguous-header-target",Some(owner),Some(row),Some(&key)));continue}let Some(target)=placed.iter().find(|c|Rc::ptr_eq(&c.owner,&matches[0])).cloned()else{diagnostics.push(table_diagnostic("unprojectable-header-target",Some(owner),Some(row),Some(&key)));continue};if let Some(index)=source{let cell=&mut placed[index];if owner.borrow().modules.topology.table.role=="headerCell"&&(target.row>cell.row||target.row==cell.row&&target.column>=cell.column){diagnostics.push(table_diagnostic("non-upstream-header-target",Some(owner),Some(row),Some(&key)));continue}let target_ref=table_ref(&target.owner);cell.ordered_headers.push(target_ref.clone());if target.kind=="row-header"{cell.row_headers.push(target_ref)}else{cell.column_headers.push(target_ref)}}}}}
        let valid=diagnostics.is_empty();let row_values:Vec<_>=rows.iter().enumerate().map(|(index,row)|{let cells=placed.iter().filter(|c|c.row==index).map(|cell|record(vec![("ref",table_ref(&cell.owner)),("kind",Value::string(&cell.kind)),("row",Value::number(cell.row as f64)),("column",Value::number(cell.column as f64)),("rowSpan",Value::number(cell.row_span as f64)),("columnSpan",Value::number(cell.column_span as f64)),("columnHeaders",Value::Array(Rc::new(cell.column_headers.clone()))),("rowHeaders",Value::Array(Rc::new(cell.row_headers.clone()))),("orderedHeaders",Value::Array(Rc::new(cell.ordered_headers.clone())))] )).collect();record(vec![("ref",table_ref(row)),("index",Value::number(index as f64)),("cells",Value::Array(Rc::new(cells)))])}).collect();let caption=if captions.len()==1{table_ref(&captions[0])}else{Value::Undefined};let snapshot=record(vec![("root",table_ref(root)),("caption",caption.clone()),("rowCount",Value::number(rows.len()as f64)),("columnCount",Value::number(column_count as f64)),("rows",Value::Array(Rc::new(row_values))),("valid",Value::boolean(valid)),("diagnostics",Value::Array(Rc::new(diagnostics)))]);root.borrow_mut().modules.topology.table.snapshot=snapshot;
        if !valid{continue}internal_state(root,"table.a11yRole",Value::string("table"));internal_state(root,"table.rowCount",Value::number(rows.len()as f64));internal_state(root,"table.columnCount",Value::number(column_count as f64));if captions.len()==1{internal_state(&captions[0],"table.a11yRole",Value::string("caption"));table_relation(root,"labelledBy",vec![caption]);}for(index,row)in rows.iter().enumerate(){internal_state(row,"table.a11yRole",Value::string("row"));internal_state(row,"table.row",Value::number(index as f64+1.));}for cell in placed{let role=match cell.kind.as_str(){"column-header"=>"columnheader","row-header"=>"rowheader",_=>"cell"};internal_state(&cell.owner,"table.a11yRole",Value::string(role));internal_state(&cell.owner,"table.row",Value::number(cell.row as f64+1.));internal_state(&cell.owner,"table.column",Value::number(cell.column as f64+1.));internal_state(&cell.owner,"table.rowSpan",Value::number(cell.row_span as f64));internal_state(&cell.owner,"table.columnSpan",Value::number(cell.column_span as f64));if !cell.ordered_headers.is_empty(){let mut labels=cell.ordered_headers;labels.push(table_ref(&cell.owner));table_relation(&cell.owner,"labelledBy",labels);}}
    }
}
`;
