// Logical ownership is independent of GPUI physical wrappers and deferred layers.
export const gpuiNativeTopologySource = String.raw`
#[derive(Clone)]
pub struct AnatomyClaim{pub family:&'static StaticDeclaration,pub role:String,pub profile:Option<String>}
#[derive(Clone)]
pub struct AnatomyWatch{pub family:&'static StaticDeclaration,pub role:String,pub active:Rc<Cell<bool>>,pub callback:Value,pub signature:Vec<usize>}
#[derive(Default)]
pub struct Topology{pub claims:BTreeMap<&'static str,AnatomyClaim>,pub subscriptions:Vec<AnatomyWatch>,pub signatures:BTreeMap<&'static str,Vec<usize>>,pub versions:BTreeMap<&'static str,u64>,pub collection:BTreeMap<String,Value>,pub item:BTreeMap<String,Value>,pub handles:BTreeMap<String,Value>,pub table:TableModule,pub order:u64}
thread_local!{static HOST_ORDER:Cell<u64>=Cell::new(0);static TOPOLOGY_UPDATING:Cell<bool>=Cell::new(false);}
pub fn note_host_order(owner:&OwnerRef){HOST_ORDER.with(|n|{let order=n.get().wrapping_add(1);n.set(order);owner.borrow_mut().modules.topology.order=order;});}
pub fn declaration(value:&Value,kind:&str)->&'static StaticDeclaration{match value{Value::StaticCapability(value) if value.kind==kind=>value,_=>panic!("expected nominal {kind} declaration")}}
pub fn anatomy_claim(owner:&OwnerWeak,family:Value,config:Value)->Value{
    let owner=setup(owner);let family=declaration(&family,"anatomy-family");let role=config.member("role",false).text();let declaration=(family.config)();assert!(!declaration.member("roles",false).member(&role,false).nullish(),"undeclared Anatomy role");let profile=config.member("profile",false);let profile=if profile.nullish(){None}else{let name=profile.text();assert!(!declaration.member("profiles",true).member(&name,true).nullish(),"unknown Anatomy profile");Some(name)};
    let mut o=owner.borrow_mut();assert!(!o.modules.topology.claims.contains_key(family.id),"duplicate Anatomy family claim");o.modules.topology.claims.insert(family.id,AnatomyClaim{family,role,profile});Value::Undefined
}
fn anatomy_root(owner:&OwnerRef,family:&str)->Option<OwnerRef>{let mut current=Some(owner.clone());let mut visited=BTreeSet::new();while let Some(candidate)=current{assert!(visited.insert(Rc::as_ptr(&candidate)as usize),"cyclic Anatomy ancestry");let o=candidate.borrow();let is_root=o.modules.topology.claims.get(family).is_some_and(|c|c.role=="root");current=o.parent.upgrade();drop(o);if is_root{return Some(candidate)}}None}
fn anatomy_members(owner:&OwnerRef,family:&str,role:Option<&str>,strict:bool)->Vec<OwnerRef>{let Some(root)=anatomy_root(owner,family)else{assert!(!strict,"current owner is not in an Anatomy domain");return vec![]};let mut parts:Vec<_>=all_owners().into_iter().filter(|part|{let p=part.borrow();let included=p.mounted&&p.present&&p.modules.topology.claims.get(family).is_some_and(|claim|role.map_or(true,|role|claim.role==role));drop(p);included&&anatomy_root(part,family).is_some_and(|r|Rc::ptr_eq(&r,&root))}).collect();parts.sort_by_key(|p|p.borrow().modules.topology.order);parts}
pub fn anatomy_parts(owner:&OwnerWeak,family:Value,role:Value)->Value{let owner=ensure(owner);let family=declaration(&family,"anatomy-family");let role=if role.nullish(){None}else{Some(role.text())};Value::Array(Rc::new(anatomy_members(&owner,family.id,role.as_deref(),true).into_iter().map(|part|{let role=part.borrow().modules.topology.claims[family.id].role.clone();Value::Part(Rc::downgrade(&part),role)}).collect()))}
pub fn anatomy_has(owner:&OwnerWeak,family:Value,role:Value)->Value{Value::boolean(!anatomy_parts(owner,family,role).items().is_empty())}
pub fn anatomy_version(owner:&OwnerWeak,family:Value)->Value{let owner=ensure(owner);let family=declaration(&family,"anatomy-family");let root=anatomy_root(&owner,family.id).expect("current owner is not in an Anatomy domain");let version=root.borrow().modules.topology.versions.get(family.id).copied().unwrap_or(0);Value::number(version as f64)}
pub fn anatomy_neighbor(owner:&OwnerWeak,family:Value,role:Value,delta:i32)->Value{let owner_ref=ensure(owner);let parts=anatomy_parts(owner,family,role).items();let index=parts.iter().position(|part|Weak::ptr_eq(&part.owner(),&Rc::downgrade(&owner_ref)));if delta==0{return Value::number(index.map_or(-1.,|i|i as f64))}index.and_then(|i|{let next=i as isize+delta as isize;if next<0{None}else{parts.get(next as usize).cloned()}}).unwrap_or(Value::Json(Json::Null))}
pub fn anatomy_subscribe(owner:&OwnerWeak,family:Value,role:Value,callback:Value)->Value{let owner=setup(owner);let family=declaration(&family,"anatomy-family");let role=role.text();let signature=anatomy_members(&owner,family.id,Some(&role),false).iter().map(|p|Rc::as_ptr(p)as usize).collect();let active=Rc::new(Cell::new(true));owner.borrow_mut().modules.topology.subscriptions.push(AnatomyWatch{family,role,callback,signature,active:active.clone()});disposer(owner,active,true)}
pub fn part_has_expose(part:Value,key:Value)->Value{Value::boolean(ensure(&part.owner()).borrow().exposes.contains_key(&key.text()))}
pub fn part_get_expose(part:Value,key:Value)->Value{ensure(&part.owner()).borrow().exposes.get(&key.text()).cloned().unwrap_or(Value::Json(Json::Null))}
pub fn part_has_hook(part:Value,key:Value)->Value{let key=key.text();let kind=match key.as_str(){"asFocusable"=>"focus","asFocusEntry"=>"focus-entry","asFocusScope"=>"focus-scope","asFocusRoving"=>"focus-roving","asAccessible"=>"accessible","asCollection"=>"collection","asCollectionItem"=>"collection-item","asOverlay"=>"overlay","asTrigger"=>"trigger",_=>key.as_str()};Value::boolean(ensure(&part.owner()).borrow().modules.hooks.contains(kind))}
fn owned_state(owner:&OwnerWeak,key:&str,kind:&'static str,value:Value)->Value{create_state(owner,kind,Value::string(key),value,Value::Undefined)}
fn internal_state(owner:&OwnerRef,key:&str,value:Value){let handle=owner.borrow().modules.topology.handles.get(key).cloned();if let Some(Value::State(state))=handle{write_state_value(&state,value,Value::string("native-topology"));}}
pub fn collection_setup(owner:&OwnerWeak,item:bool)->Value{
    let kind=if item{"collection-item"}else{"collection"};let handle=module_handle(owner,kind);let owner_ref=ensure(owner);if item{for(key,name,value,kind)in[("collectionIndex","collectionIndex",Value::number(-1.),"discrete"),("collectionTotal","collectionTotal",Value::number(0.),"discrete"),("collectionFirst","collectionFirst",Value::boolean(false),"bool"),("collectionLast","collectionLast",Value::boolean(false),"bool")]{if !owner_ref.borrow().modules.topology.handles.contains_key(key){let state=owned_state(owner,name,kind,value);owner_ref.borrow_mut().modules.topology.handles.insert(key.into(),state);}}}else if !owner_ref.borrow().modules.topology.handles.contains_key("count"){let state=owned_state(owner,"collectionCount","discrete",Value::number(0.));owner_ref.borrow_mut().modules.topology.handles.insert("count".into(),state);}handle
}
pub fn collection_configure(owner:&OwnerWeak,patch:Value,item:bool)->Value{
    let owner_ref=setup(owner);let family=patch.member("family",false);declaration(&family,"anatomy-family");let config=match patch{Value::Record(entries)=>(*entries).clone(),_=>panic!("Collection config required")};
    if item{let role=text_or(field(&config,"role"),"item");anatomy_claim(owner,family,record(vec![("role",Value::string(&role))]));owner_ref.borrow_mut().modules.topology.item=config.clone();for(key,option,default)in[("collectionIndex","exposeIndexStateKey","collectionIndex"),("collectionTotal","exposeTotalStateKey","collectionTotal"),("collectionFirst","exposeFirstStateKey","collectionFirst"),("collectionLast","exposeLastStateKey","collectionLast")]{let state=owner_ref.borrow().modules.topology.handles[key].clone();expose_state(owner,Value::string(&text_or(field(&config,option),default)),state);}let key=text_or(field(&config,"exposeSnapshotMethodKey"),"getCollectionItem");let weak=owner.clone();expose_method(owner,Value::string(&key),Value::Function(Rc::new(move |_|collection_item_snapshot(&weak))));let meta_key=text_or(field(&config,"metaExposeKey"),"__collectionItem");let weak=owner.clone();expose_method(owner,Value::string(&meta_key),Value::Function(Rc::new(move |_|collection_item_meta(&weak))));
    }else{let role=field(&config,"ownerRole");let role=if role.nullish(){field(&config,"rootRole")}else{role};if !role.nullish()&&!matches!(role,Value::Json(Json::Bool(false))){anatomy_claim(owner,family,record(vec![("role",role)]));}owner_ref.borrow_mut().modules.topology.collection=config.clone();let count=owner_ref.borrow().modules.topology.handles["count"].clone();expose_state(owner,Value::string(&text_or(field(&config,"exposeCountStateKey"),"count")),count);let weak=owner.clone();expose_method(owner,Value::string(&text_or(field(&config,"exposeItemsMethodKey"),"getCollectionItems")),Value::Function(Rc::new(move |_|collection_items(&weak))));let weak=owner.clone();expose_method(owner,Value::string(&text_or(field(&config,"exposeCountMethodKey"),"getCollectionCount")),Value::Function(Rc::new(move |_|collection_count(&weak))));}
    Value::Undefined
}
fn collection_item_meta(owner:&OwnerWeak)->Value{let owner_ref=ensure(owner);let callback=field(&owner_ref.borrow().modules.topology.item,"getMeta");if callback.nullish(){record(vec![])}else{invoke(&owner_ref,"expose-method",&callback,vec![capability(owner)])}}
fn collection_position(owner:&OwnerRef)->(i64,usize){let config=owner.borrow().modules.topology.item.clone();let family=field(&config,"family");if family.nullish(){return(-1,0)}let family=declaration(&family,"anatomy-family");let role=text_or(field(&config,"role"),"item");let parts=anatomy_members(owner,family.id,Some(&role),false);(parts.iter().position(|p|Rc::ptr_eq(p,owner)).map_or(-1,|i|i as i64),parts.len())}
pub fn collection_item_snapshot(owner:&OwnerWeak)->Value{let owner_ref=ensure(owner);let(index,total)=collection_position(&owner_ref);let meta=collection_item_meta(owner);let Value::Record(meta)=meta else{panic!("Collection item metadata must be portable record")};let mut fields=(*meta).clone();fields.insert("index".into(),Value::number(index as f64));fields.insert("total".into(),Value::number(total as f64));fields.insert("first".into(),Value::boolean(index==0));fields.insert("last".into(),Value::boolean(index>=0&&index as usize+1==total));Value::Record(Rc::new(fields))}
pub fn collection_items(owner:&OwnerWeak)->Value{let owner=ensure(owner);let config=owner.borrow().modules.topology.collection.clone();let family=field(&config,"family");if family.nullish(){return Value::Array(Rc::new(vec![]))}let family=declaration(&family,"anatomy-family");let role=text_or(field(&config,"itemRole"),"item");let meta_key=text_or(field(&config,"itemMetaExposeKey"),"__collectionItem");let parts=anatomy_members(&owner,family.id,Some(&role),false);let total=parts.len();Value::Array(Rc::new(parts.into_iter().enumerate().map(|(index,part)|{let meta=part.borrow().exposes.get(&meta_key).cloned();let meta=match meta{Some(Value::Function(f))=>invoke(&part,"expose-method",&Value::Function(f),vec![]),Some(value)=>value,None=>record(vec![])};let Value::Record(meta)=meta else{panic!("Collection item metadata must be portable record")};let mut fields=(*meta).clone();fields.insert("index".into(),Value::number(index as f64));fields.insert("total".into(),Value::number(total as f64));fields.insert("first".into(),Value::boolean(index==0));fields.insert("last".into(),Value::boolean(index+1==total));Value::Record(Rc::new(fields))}).collect()))}
pub fn collection_count(owner:&OwnerWeak)->Value{Value::number(collection_items(owner).items().len()as f64)}
pub fn topology_refresh(){
    if TOPOLOGY_UPDATING.with(|flag|flag.replace(true)){return}struct Reset;impl Drop for Reset{fn drop(&mut self){TOPOLOGY_UPDATING.with(|flag|flag.set(false));}}let _reset=Reset;
    let owners=all_owners();let mut callbacks=Vec::new();
    for owner in &owners{let claims=owner.borrow().modules.topology.claims.clone();for(id,claim)in claims{if claim.role=="root"{let signature:Vec<_>=anatomy_members(owner,id,None,false).iter().map(|p|Rc::as_ptr(p)as usize).collect();let changed=owner.borrow().modules.topology.signatures.get(id)!=Some(&signature);if changed{let mut o=owner.borrow_mut();o.modules.topology.signatures.insert(id,signature);*o.modules.topology.versions.entry(id).or_default()+=1;}}}
        if owner.borrow().mounted{let watches=owner.borrow().modules.topology.subscriptions.clone();for(index,watch)in watches.into_iter().enumerate(){if !watch.active.get(){continue}let parts=anatomy_members(owner,watch.family.id,Some(&watch.role),false);let signature:Vec<_>=parts.iter().map(|p|Rc::as_ptr(p)as usize).collect();if signature!=watch.signature{owner.borrow_mut().modules.topology.subscriptions[index].signature=signature;callbacks.push((owner.clone(),watch.callback,Value::Array(Rc::new(parts.into_iter().map(|p|Value::Part(Rc::downgrade(&p),watch.role.clone())).collect()))));}}}
        if !owner.borrow().modules.topology.collection.is_empty(){let config=owner.borrow().modules.topology.collection.clone();let family=field(&config,"family");let family=declaration(&family,"anatomy-family");let role=text_or(field(&config,"itemRole"),"item");let count=anatomy_members(owner,family.id,Some(&role),false).len();internal_state(owner,"count",Value::number(count as f64));}
        if !owner.borrow().modules.topology.item.is_empty(){let(index,total)=collection_position(owner);internal_state(owner,"collectionIndex",Value::number(index as f64));internal_state(owner,"collectionTotal",Value::number(total as f64));internal_state(owner,"collectionFirst",Value::boolean(index==0));internal_state(owner,"collectionLast",Value::boolean(index>=0&&index as usize+1==total));}
    }
    table_refresh(&owners);
    for(owner,callback,parts)in callbacks{if !owner.borrow().disposed&&owner.borrow().mounted{invoke(&owner,"mounted",&callback,vec![capability(&Rc::downgrade(&owner)),parts]);}}
}
`;
