import type { Operation, Phase, ValueType } from './ir';

export interface OperationRule {
  receiver: ValueType;
  path: string;
  phases: readonly Phase[];
  result: ValueType;
  min: number;
  max: number;
  callback?: { at: number; phase: Phase; parameters: readonly ValueType[] };
}

/** One admission/emission vocabulary. Runtime-backed lowering preserves these calls in source order. */
export const OPERATION_RULES: Record<Operation, OperationRule> = {
  'hook.asTrigger': {
    receiver: 'void',
    path: 'asTrigger',
    phases: ['setup'],
    result: 'void',
    min: 0,
    max: 0,
  },
  'hook.asFocusable': {
    receiver: 'void',
    path: 'asFocusable',
    phases: ['setup'],
    result: 'focus',
    min: 0,
    max: 0,
  },
  'hook.asAccessible': {
    receiver: 'void',
    path: 'asAccessible',
    phases: ['setup'],
    result: 'accessible',
    min: 0,
    max: 0,
  },
  'props.define': {
    receiver: 'def',
    path: 'props.define',
    phases: ['setup'],
    result: 'void',
    min: 1,
    max: 1,
  },
  'props.setDefaults': {
    receiver: 'def',
    path: 'props.setDefaults',
    phases: ['setup'],
    result: 'void',
    min: 1,
    max: 1,
  },
  'props.watch': {
    receiver: 'def',
    path: 'props.watch',
    phases: ['setup'],
    result: 'void',
    min: 2,
    max: 2,
    callback: { at: 1, phase: 'callback', parameters: ['run', 'props', 'props'] },
  },
  'props.get': {
    receiver: 'run',
    path: 'props.get',
    phases: ['callback', 'render'],
    result: 'props',
    min: 0,
    max: 0,
  },
  'state.bool': {
    receiver: 'def',
    path: 'state.bool',
    phases: ['setup'],
    result: 'state:boolean',
    min: 2,
    max: 2,
  },
  'state.string': {
    receiver: 'def',
    path: 'state.string',
    phases: ['setup'],
    result: 'state:string',
    min: 2,
    max: 3,
  },
  'state.numberDiscrete': {
    receiver: 'def',
    path: 'state.numberDiscrete',
    phases: ['setup'],
    result: 'state:number',
    min: 2,
    max: 3,
  },
  'state.numberRange': {
    receiver: 'def',
    path: 'state.numberRange',
    phases: ['setup'],
    result: 'state:number',
    min: 3,
    max: 3,
  },
  'state.get': {
    receiver: 'state:boolean',
    path: 'get',
    phases: ['callback', 'render'],
    result: 'unknown',
    min: 0,
    max: 0,
  },
  'state.set': {
    receiver: 'state:boolean',
    path: 'set',
    phases: ['callback'],
    result: 'void',
    min: 1,
    max: 2,
  },
  'expose.state': {
    receiver: 'def',
    path: 'expose.state',
    phases: ['setup'],
    result: 'void',
    min: 2,
    max: 2,
  },
  'expose.event': {
    receiver: 'def',
    path: 'expose.event',
    phases: ['setup'],
    result: 'void',
    min: 2,
    max: 2,
  },
  'expose.method': {
    receiver: 'def',
    path: 'expose.method',
    phases: ['setup'],
    result: 'void',
    min: 2,
    max: 2,
    callback: { at: 1, phase: 'callback', parameters: ['focus-options'] },
  },
  'expose.emit': {
    receiver: 'run',
    path: 'expose.emit',
    phases: ['callback'],
    result: 'void',
    min: 1,
    max: 1,
  },
  'lifecycle.onCreated': {
    receiver: 'def',
    path: 'lifecycle.onCreated',
    phases: ['setup'],
    result: 'void',
    min: 1,
    max: 1,
    callback: { at: 0, phase: 'callback', parameters: ['run'] },
  },
  'lifecycle.onMounted': {
    receiver: 'def',
    path: 'lifecycle.onMounted',
    phases: ['setup'],
    result: 'void',
    min: 1,
    max: 1,
    callback: { at: 0, phase: 'callback', parameters: ['run'] },
  },
  'lifecycle.onUpdated': {
    receiver: 'def',
    path: 'lifecycle.onUpdated',
    phases: ['setup'],
    result: 'void',
    min: 1,
    max: 1,
    callback: { at: 0, phase: 'callback', parameters: ['run'] },
  },
  'lifecycle.onUnmounted': {
    receiver: 'def',
    path: 'lifecycle.onUnmounted',
    phases: ['setup'],
    result: 'void',
    min: 1,
    max: 1,
    callback: { at: 0, phase: 'callback', parameters: ['run'] },
  },
  'lifecycle.onBeforeDispose': {
    receiver: 'def',
    path: 'lifecycle.onBeforeDispose',
    phases: ['setup'],
    result: 'void',
    min: 1,
    max: 1,
    callback: { at: 0, phase: 'callback', parameters: ['run'] },
  },
  'event.on': {
    receiver: 'def',
    path: 'event.on',
    phases: ['setup'],
    result: 'void',
    min: 2,
    max: 2,
    callback: { at: 1, phase: 'callback', parameters: ['run', 'event'] },
  },
  'event.onGlobal': {
    receiver: 'def',
    path: 'event.onGlobal',
    phases: ['setup'],
    result: 'void',
    min: 2,
    max: 2,
    callback: { at: 1, phase: 'callback', parameters: ['run', 'event'] },
  },
  'event.requestDefaultActionPrevention': {
    receiver: 'event',
    path: 'requestDefaultActionPrevention',
    phases: ['callback'],
    result: 'void',
    min: 1,
    max: 1,
  },
  'focus.configure': {
    receiver: 'focus',
    path: 'configure',
    phases: ['setup'],
    result: 'void',
    min: 1,
    max: 1,
  },
  'focus.setDisabled': {
    receiver: 'focus',
    path: 'setDisabled',
    phases: ['callback'],
    result: 'void',
    min: 1,
    max: 1,
  },
  'focus.focusSelf': {
    receiver: 'focus',
    path: 'focusSelf',
    phases: ['callback'],
    result: 'void',
    min: 0,
    max: 1,
  },
  'accessible.state': {
    receiver: 'accessible',
    path: 'state',
    phases: ['setup'],
    result: 'void',
    min: 2,
    max: 2,
  },
  'accessible.action': {
    receiver: 'accessible',
    path: 'action',
    phases: ['setup'],
    result: 'void',
    min: 2,
    max: 2,
  },
  'accessible.role': {
    receiver: 'accessible',
    path: 'role',
    phases: ['setup'],
    result: 'void',
    min: 1,
    max: 1,
  },
  'accessible.nameFromContent': {
    receiver: 'accessible',
    path: 'nameFromContent',
    phases: ['setup'],
    result: 'void',
    min: 0,
    max: 0,
  },
  'render.el': {
    receiver: 'render',
    path: 'el',
    phases: ['render'],
    result: 'template',
    min: 1,
    max: 3,
  },
  'render.slot': {
    receiver: 'render',
    path: 'slot',
    phases: ['render'],
    result: 'template',
    min: 0,
    max: 0,
  },
  'render.fragment': {
    receiver: 'render',
    path: 'fragment',
    phases: ['render'],
    result: 'template',
    min: 1,
    max: 1,
  },
};
