import type { ComponentEntry } from './components';

// Workspace-only source families retain all authored atoms without a release claim.
export const FINF_WORKSPACE_COMPONENT_ENTRIES: Record<string, ComponentEntry> = {
  'base-alert-dialog': {
    'id': 'base-alert-dialog',
    'label': 'Base AlertDialog (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/alert-dialog',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'alertDialogRoot',
        'reactExport': 'BaseAlertDialogRoot',
        'vueExport': 'BaseAlertDialogRoot',
        'wcExport': 'BaseAlertDialogRootElement',
        'elementName': 'proto-ui-base-alert-dialog-root',
      },
      {
        'prototypeImport': 'alertDialogTrigger',
        'reactExport': 'BaseAlertDialogTrigger',
        'vueExport': 'BaseAlertDialogTrigger',
        'wcExport': 'BaseAlertDialogTriggerElement',
        'elementName': 'proto-ui-base-alert-dialog-trigger',
      },
      {
        'prototypeImport': 'alertDialogContent',
        'reactExport': 'BaseAlertDialogContent',
        'vueExport': 'BaseAlertDialogContent',
        'wcExport': 'BaseAlertDialogContentElement',
        'elementName': 'proto-ui-base-alert-dialog-content',
      },
      {
        'prototypeImport': 'alertDialogTitle',
        'reactExport': 'BaseAlertDialogTitle',
        'vueExport': 'BaseAlertDialogTitle',
        'wcExport': 'BaseAlertDialogTitleElement',
        'elementName': 'proto-ui-base-alert-dialog-title',
      },
      {
        'prototypeImport': 'alertDialogDescription',
        'reactExport': 'BaseAlertDialogDescription',
        'vueExport': 'BaseAlertDialogDescription',
        'wcExport': 'BaseAlertDialogDescriptionElement',
        'elementName': 'proto-ui-base-alert-dialog-description',
      },
      {
        'prototypeImport': 'alertDialogCancel',
        'reactExport': 'BaseAlertDialogCancel',
        'vueExport': 'BaseAlertDialogCancel',
        'wcExport': 'BaseAlertDialogCancelElement',
        'elementName': 'proto-ui-base-alert-dialog-cancel',
      },
      {
        'prototypeImport': 'alertDialogAction',
        'reactExport': 'BaseAlertDialogAction',
        'vueExport': 'BaseAlertDialogAction',
        'wcExport': 'BaseAlertDialogActionElement',
        'elementName': 'proto-ui-base-alert-dialog-action',
      },
      {
        'prototypeImport': 'alertDialogMask',
        'reactExport': 'BaseAlertDialogMask',
        'vueExport': 'BaseAlertDialogMask',
        'wcExport': 'BaseAlertDialogMaskElement',
        'elementName': 'proto-ui-base-alert-dialog-mask',
      },
    ],
  },
  'shadcn-alert-dialog': {
    'id': 'shadcn-alert-dialog',
    'label': 'Shadcn AlertDialog (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/alert-dialog',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'alertDialogRoot',
        'reactExport': 'ShadcnAlertDialogRoot',
        'vueExport': 'ShadcnAlertDialogRoot',
        'wcExport': 'ShadcnAlertDialogRootElement',
        'elementName': 'proto-ui-shadcn-alert-dialog-root',
      },
      {
        'prototypeImport': 'alertDialogTrigger',
        'reactExport': 'ShadcnAlertDialogTrigger',
        'vueExport': 'ShadcnAlertDialogTrigger',
        'wcExport': 'ShadcnAlertDialogTriggerElement',
        'elementName': 'proto-ui-shadcn-alert-dialog-trigger',
      },
      {
        'prototypeImport': 'alertDialogContent',
        'reactExport': 'ShadcnAlertDialogContent',
        'vueExport': 'ShadcnAlertDialogContent',
        'wcExport': 'ShadcnAlertDialogContentElement',
        'elementName': 'proto-ui-shadcn-alert-dialog-content',
      },
      {
        'prototypeImport': 'alertDialogTitle',
        'reactExport': 'ShadcnAlertDialogTitle',
        'vueExport': 'ShadcnAlertDialogTitle',
        'wcExport': 'ShadcnAlertDialogTitleElement',
        'elementName': 'proto-ui-shadcn-alert-dialog-title',
      },
      {
        'prototypeImport': 'alertDialogDescription',
        'reactExport': 'ShadcnAlertDialogDescription',
        'vueExport': 'ShadcnAlertDialogDescription',
        'wcExport': 'ShadcnAlertDialogDescriptionElement',
        'elementName': 'proto-ui-shadcn-alert-dialog-description',
      },
      {
        'prototypeImport': 'alertDialogCancel',
        'reactExport': 'ShadcnAlertDialogCancel',
        'vueExport': 'ShadcnAlertDialogCancel',
        'wcExport': 'ShadcnAlertDialogCancelElement',
        'elementName': 'proto-ui-shadcn-alert-dialog-cancel',
      },
      {
        'prototypeImport': 'alertDialogAction',
        'reactExport': 'ShadcnAlertDialogAction',
        'vueExport': 'ShadcnAlertDialogAction',
        'wcExport': 'ShadcnAlertDialogActionElement',
        'elementName': 'proto-ui-shadcn-alert-dialog-action',
      },
      {
        'prototypeImport': 'alertDialogMask',
        'reactExport': 'ShadcnAlertDialogMask',
        'vueExport': 'ShadcnAlertDialogMask',
        'wcExport': 'ShadcnAlertDialogMaskElement',
        'elementName': 'proto-ui-shadcn-alert-dialog-mask',
      },
    ],
  },
  'brutalist-alert-dialog': {
    'id': 'brutalist-alert-dialog',
    'label': 'Brutalist AlertDialog (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/alert-dialog',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'alertDialogRoot',
        'reactExport': 'BrutalistAlertDialogRoot',
        'vueExport': 'BrutalistAlertDialogRoot',
        'wcExport': 'BrutalistAlertDialogRootElement',
        'elementName': 'proto-ui-brutalist-alert-dialog-root',
      },
      {
        'prototypeImport': 'alertDialogTrigger',
        'reactExport': 'BrutalistAlertDialogTrigger',
        'vueExport': 'BrutalistAlertDialogTrigger',
        'wcExport': 'BrutalistAlertDialogTriggerElement',
        'elementName': 'proto-ui-brutalist-alert-dialog-trigger',
      },
      {
        'prototypeImport': 'alertDialogContent',
        'reactExport': 'BrutalistAlertDialogContent',
        'vueExport': 'BrutalistAlertDialogContent',
        'wcExport': 'BrutalistAlertDialogContentElement',
        'elementName': 'proto-ui-brutalist-alert-dialog-content',
      },
      {
        'prototypeImport': 'alertDialogTitle',
        'reactExport': 'BrutalistAlertDialogTitle',
        'vueExport': 'BrutalistAlertDialogTitle',
        'wcExport': 'BrutalistAlertDialogTitleElement',
        'elementName': 'proto-ui-brutalist-alert-dialog-title',
      },
      {
        'prototypeImport': 'alertDialogDescription',
        'reactExport': 'BrutalistAlertDialogDescription',
        'vueExport': 'BrutalistAlertDialogDescription',
        'wcExport': 'BrutalistAlertDialogDescriptionElement',
        'elementName': 'proto-ui-brutalist-alert-dialog-description',
      },
      {
        'prototypeImport': 'alertDialogCancel',
        'reactExport': 'BrutalistAlertDialogCancel',
        'vueExport': 'BrutalistAlertDialogCancel',
        'wcExport': 'BrutalistAlertDialogCancelElement',
        'elementName': 'proto-ui-brutalist-alert-dialog-cancel',
      },
      {
        'prototypeImport': 'alertDialogAction',
        'reactExport': 'BrutalistAlertDialogAction',
        'vueExport': 'BrutalistAlertDialogAction',
        'wcExport': 'BrutalistAlertDialogActionElement',
        'elementName': 'proto-ui-brutalist-alert-dialog-action',
      },
      {
        'prototypeImport': 'alertDialogMask',
        'reactExport': 'BrutalistAlertDialogMask',
        'vueExport': 'BrutalistAlertDialogMask',
        'wcExport': 'BrutalistAlertDialogMaskElement',
        'elementName': 'proto-ui-brutalist-alert-dialog-mask',
      },
    ],
  },
  'bootstrap-2-3-2-alert-dialog': {
    'id': 'bootstrap-2-3-2-alert-dialog',
    'label': 'Bootstrap232 AlertDialog (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/alert-dialog',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'alertDialogRoot',
        'reactExport': 'Bootstrap232AlertDialogRoot',
        'vueExport': 'Bootstrap232AlertDialogRoot',
        'wcExport': 'Bootstrap232AlertDialogRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-alert-dialog-root',
      },
      {
        'prototypeImport': 'alertDialogTrigger',
        'reactExport': 'Bootstrap232AlertDialogTrigger',
        'vueExport': 'Bootstrap232AlertDialogTrigger',
        'wcExport': 'Bootstrap232AlertDialogTriggerElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-alert-dialog-trigger',
      },
      {
        'prototypeImport': 'alertDialogContent',
        'reactExport': 'Bootstrap232AlertDialogContent',
        'vueExport': 'Bootstrap232AlertDialogContent',
        'wcExport': 'Bootstrap232AlertDialogContentElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-alert-dialog-content',
      },
      {
        'prototypeImport': 'alertDialogTitle',
        'reactExport': 'Bootstrap232AlertDialogTitle',
        'vueExport': 'Bootstrap232AlertDialogTitle',
        'wcExport': 'Bootstrap232AlertDialogTitleElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-alert-dialog-title',
      },
      {
        'prototypeImport': 'alertDialogDescription',
        'reactExport': 'Bootstrap232AlertDialogDescription',
        'vueExport': 'Bootstrap232AlertDialogDescription',
        'wcExport': 'Bootstrap232AlertDialogDescriptionElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-alert-dialog-description',
      },
      {
        'prototypeImport': 'alertDialogCancel',
        'reactExport': 'Bootstrap232AlertDialogCancel',
        'vueExport': 'Bootstrap232AlertDialogCancel',
        'wcExport': 'Bootstrap232AlertDialogCancelElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-alert-dialog-cancel',
      },
      {
        'prototypeImport': 'alertDialogAction',
        'reactExport': 'Bootstrap232AlertDialogAction',
        'vueExport': 'Bootstrap232AlertDialogAction',
        'wcExport': 'Bootstrap232AlertDialogActionElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-alert-dialog-action',
      },
      {
        'prototypeImport': 'alertDialogMask',
        'reactExport': 'Bootstrap232AlertDialogMask',
        'vueExport': 'Bootstrap232AlertDialogMask',
        'wcExport': 'Bootstrap232AlertDialogMaskElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-alert-dialog-mask',
      },
    ],
  },
  'liquid-glass-alert-dialog': {
    'id': 'liquid-glass-alert-dialog',
    'label': 'LiquidGlass AlertDialog (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/alert-dialog',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'alertDialogRoot',
        'reactExport': 'LiquidGlassAlertDialogRoot',
        'vueExport': 'LiquidGlassAlertDialogRoot',
        'wcExport': 'LiquidGlassAlertDialogRootElement',
        'elementName': 'proto-ui-liquid-glass-alert-dialog-root',
      },
      {
        'prototypeImport': 'alertDialogTrigger',
        'reactExport': 'LiquidGlassAlertDialogTrigger',
        'vueExport': 'LiquidGlassAlertDialogTrigger',
        'wcExport': 'LiquidGlassAlertDialogTriggerElement',
        'elementName': 'proto-ui-liquid-glass-alert-dialog-trigger',
      },
      {
        'prototypeImport': 'alertDialogContent',
        'reactExport': 'LiquidGlassAlertDialogContent',
        'vueExport': 'LiquidGlassAlertDialogContent',
        'wcExport': 'LiquidGlassAlertDialogContentElement',
        'elementName': 'proto-ui-liquid-glass-alert-dialog-content',
      },
      {
        'prototypeImport': 'alertDialogTitle',
        'reactExport': 'LiquidGlassAlertDialogTitle',
        'vueExport': 'LiquidGlassAlertDialogTitle',
        'wcExport': 'LiquidGlassAlertDialogTitleElement',
        'elementName': 'proto-ui-liquid-glass-alert-dialog-title',
      },
      {
        'prototypeImport': 'alertDialogDescription',
        'reactExport': 'LiquidGlassAlertDialogDescription',
        'vueExport': 'LiquidGlassAlertDialogDescription',
        'wcExport': 'LiquidGlassAlertDialogDescriptionElement',
        'elementName': 'proto-ui-liquid-glass-alert-dialog-description',
      },
      {
        'prototypeImport': 'alertDialogCancel',
        'reactExport': 'LiquidGlassAlertDialogCancel',
        'vueExport': 'LiquidGlassAlertDialogCancel',
        'wcExport': 'LiquidGlassAlertDialogCancelElement',
        'elementName': 'proto-ui-liquid-glass-alert-dialog-cancel',
      },
      {
        'prototypeImport': 'alertDialogAction',
        'reactExport': 'LiquidGlassAlertDialogAction',
        'vueExport': 'LiquidGlassAlertDialogAction',
        'wcExport': 'LiquidGlassAlertDialogActionElement',
        'elementName': 'proto-ui-liquid-glass-alert-dialog-action',
      },
      {
        'prototypeImport': 'alertDialogMask',
        'reactExport': 'LiquidGlassAlertDialogMask',
        'vueExport': 'LiquidGlassAlertDialogMask',
        'wcExport': 'LiquidGlassAlertDialogMaskElement',
        'elementName': 'proto-ui-liquid-glass-alert-dialog-mask',
      },
    ],
  },
  'base-drawer': {
    'id': 'base-drawer',
    'label': 'Base Drawer (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/drawer',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'drawerRoot',
        'reactExport': 'BaseDrawerRoot',
        'vueExport': 'BaseDrawerRoot',
        'wcExport': 'BaseDrawerRootElement',
        'elementName': 'proto-ui-base-drawer-root',
      },
      {
        'prototypeImport': 'drawerTrigger',
        'reactExport': 'BaseDrawerTrigger',
        'vueExport': 'BaseDrawerTrigger',
        'wcExport': 'BaseDrawerTriggerElement',
        'elementName': 'proto-ui-base-drawer-trigger',
      },
      {
        'prototypeImport': 'drawerContent',
        'reactExport': 'BaseDrawerContent',
        'vueExport': 'BaseDrawerContent',
        'wcExport': 'BaseDrawerContentElement',
        'elementName': 'proto-ui-base-drawer-content',
      },
      {
        'prototypeImport': 'drawerTitle',
        'reactExport': 'BaseDrawerTitle',
        'vueExport': 'BaseDrawerTitle',
        'wcExport': 'BaseDrawerTitleElement',
        'elementName': 'proto-ui-base-drawer-title',
      },
      {
        'prototypeImport': 'drawerDescription',
        'reactExport': 'BaseDrawerDescription',
        'vueExport': 'BaseDrawerDescription',
        'wcExport': 'BaseDrawerDescriptionElement',
        'elementName': 'proto-ui-base-drawer-description',
      },
      {
        'prototypeImport': 'drawerClose',
        'reactExport': 'BaseDrawerClose',
        'vueExport': 'BaseDrawerClose',
        'wcExport': 'BaseDrawerCloseElement',
        'elementName': 'proto-ui-base-drawer-close',
      },
      {
        'prototypeImport': 'drawerMask',
        'reactExport': 'BaseDrawerMask',
        'vueExport': 'BaseDrawerMask',
        'wcExport': 'BaseDrawerMaskElement',
        'elementName': 'proto-ui-base-drawer-mask',
      },
    ],
  },
  'shadcn-drawer': {
    'id': 'shadcn-drawer',
    'label': 'Shadcn Drawer (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/drawer',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'drawerRoot',
        'reactExport': 'ShadcnDrawerRoot',
        'vueExport': 'ShadcnDrawerRoot',
        'wcExport': 'ShadcnDrawerRootElement',
        'elementName': 'proto-ui-shadcn-drawer-root',
      },
      {
        'prototypeImport': 'drawerTrigger',
        'reactExport': 'ShadcnDrawerTrigger',
        'vueExport': 'ShadcnDrawerTrigger',
        'wcExport': 'ShadcnDrawerTriggerElement',
        'elementName': 'proto-ui-shadcn-drawer-trigger',
      },
      {
        'prototypeImport': 'drawerContent',
        'reactExport': 'ShadcnDrawerContent',
        'vueExport': 'ShadcnDrawerContent',
        'wcExport': 'ShadcnDrawerContentElement',
        'elementName': 'proto-ui-shadcn-drawer-content',
      },
      {
        'prototypeImport': 'drawerTitle',
        'reactExport': 'ShadcnDrawerTitle',
        'vueExport': 'ShadcnDrawerTitle',
        'wcExport': 'ShadcnDrawerTitleElement',
        'elementName': 'proto-ui-shadcn-drawer-title',
      },
      {
        'prototypeImport': 'drawerDescription',
        'reactExport': 'ShadcnDrawerDescription',
        'vueExport': 'ShadcnDrawerDescription',
        'wcExport': 'ShadcnDrawerDescriptionElement',
        'elementName': 'proto-ui-shadcn-drawer-description',
      },
      {
        'prototypeImport': 'drawerClose',
        'reactExport': 'ShadcnDrawerClose',
        'vueExport': 'ShadcnDrawerClose',
        'wcExport': 'ShadcnDrawerCloseElement',
        'elementName': 'proto-ui-shadcn-drawer-close',
      },
      {
        'prototypeImport': 'drawerMask',
        'reactExport': 'ShadcnDrawerMask',
        'vueExport': 'ShadcnDrawerMask',
        'wcExport': 'ShadcnDrawerMaskElement',
        'elementName': 'proto-ui-shadcn-drawer-mask',
      },
    ],
  },
  'brutalist-drawer': {
    'id': 'brutalist-drawer',
    'label': 'Brutalist Drawer (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/drawer',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'drawerRoot',
        'reactExport': 'BrutalistDrawerRoot',
        'vueExport': 'BrutalistDrawerRoot',
        'wcExport': 'BrutalistDrawerRootElement',
        'elementName': 'proto-ui-brutalist-drawer-root',
      },
      {
        'prototypeImport': 'drawerTrigger',
        'reactExport': 'BrutalistDrawerTrigger',
        'vueExport': 'BrutalistDrawerTrigger',
        'wcExport': 'BrutalistDrawerTriggerElement',
        'elementName': 'proto-ui-brutalist-drawer-trigger',
      },
      {
        'prototypeImport': 'drawerContent',
        'reactExport': 'BrutalistDrawerContent',
        'vueExport': 'BrutalistDrawerContent',
        'wcExport': 'BrutalistDrawerContentElement',
        'elementName': 'proto-ui-brutalist-drawer-content',
      },
      {
        'prototypeImport': 'drawerTitle',
        'reactExport': 'BrutalistDrawerTitle',
        'vueExport': 'BrutalistDrawerTitle',
        'wcExport': 'BrutalistDrawerTitleElement',
        'elementName': 'proto-ui-brutalist-drawer-title',
      },
      {
        'prototypeImport': 'drawerDescription',
        'reactExport': 'BrutalistDrawerDescription',
        'vueExport': 'BrutalistDrawerDescription',
        'wcExport': 'BrutalistDrawerDescriptionElement',
        'elementName': 'proto-ui-brutalist-drawer-description',
      },
      {
        'prototypeImport': 'drawerClose',
        'reactExport': 'BrutalistDrawerClose',
        'vueExport': 'BrutalistDrawerClose',
        'wcExport': 'BrutalistDrawerCloseElement',
        'elementName': 'proto-ui-brutalist-drawer-close',
      },
      {
        'prototypeImport': 'drawerMask',
        'reactExport': 'BrutalistDrawerMask',
        'vueExport': 'BrutalistDrawerMask',
        'wcExport': 'BrutalistDrawerMaskElement',
        'elementName': 'proto-ui-brutalist-drawer-mask',
      },
    ],
  },
  'bootstrap-2-3-2-drawer': {
    'id': 'bootstrap-2-3-2-drawer',
    'label': 'Bootstrap232 Drawer (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/drawer',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'drawerRoot',
        'reactExport': 'Bootstrap232DrawerRoot',
        'vueExport': 'Bootstrap232DrawerRoot',
        'wcExport': 'Bootstrap232DrawerRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-drawer-root',
      },
      {
        'prototypeImport': 'drawerTrigger',
        'reactExport': 'Bootstrap232DrawerTrigger',
        'vueExport': 'Bootstrap232DrawerTrigger',
        'wcExport': 'Bootstrap232DrawerTriggerElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-drawer-trigger',
      },
      {
        'prototypeImport': 'drawerContent',
        'reactExport': 'Bootstrap232DrawerContent',
        'vueExport': 'Bootstrap232DrawerContent',
        'wcExport': 'Bootstrap232DrawerContentElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-drawer-content',
      },
      {
        'prototypeImport': 'drawerTitle',
        'reactExport': 'Bootstrap232DrawerTitle',
        'vueExport': 'Bootstrap232DrawerTitle',
        'wcExport': 'Bootstrap232DrawerTitleElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-drawer-title',
      },
      {
        'prototypeImport': 'drawerDescription',
        'reactExport': 'Bootstrap232DrawerDescription',
        'vueExport': 'Bootstrap232DrawerDescription',
        'wcExport': 'Bootstrap232DrawerDescriptionElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-drawer-description',
      },
      {
        'prototypeImport': 'drawerClose',
        'reactExport': 'Bootstrap232DrawerClose',
        'vueExport': 'Bootstrap232DrawerClose',
        'wcExport': 'Bootstrap232DrawerCloseElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-drawer-close',
      },
      {
        'prototypeImport': 'drawerMask',
        'reactExport': 'Bootstrap232DrawerMask',
        'vueExport': 'Bootstrap232DrawerMask',
        'wcExport': 'Bootstrap232DrawerMaskElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-drawer-mask',
      },
    ],
  },
  'liquid-glass-drawer': {
    'id': 'liquid-glass-drawer',
    'label': 'LiquidGlass Drawer (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/drawer',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'drawerRoot',
        'reactExport': 'LiquidGlassDrawerRoot',
        'vueExport': 'LiquidGlassDrawerRoot',
        'wcExport': 'LiquidGlassDrawerRootElement',
        'elementName': 'proto-ui-liquid-glass-drawer-root',
      },
      {
        'prototypeImport': 'drawerTrigger',
        'reactExport': 'LiquidGlassDrawerTrigger',
        'vueExport': 'LiquidGlassDrawerTrigger',
        'wcExport': 'LiquidGlassDrawerTriggerElement',
        'elementName': 'proto-ui-liquid-glass-drawer-trigger',
      },
      {
        'prototypeImport': 'drawerContent',
        'reactExport': 'LiquidGlassDrawerContent',
        'vueExport': 'LiquidGlassDrawerContent',
        'wcExport': 'LiquidGlassDrawerContentElement',
        'elementName': 'proto-ui-liquid-glass-drawer-content',
      },
      {
        'prototypeImport': 'drawerTitle',
        'reactExport': 'LiquidGlassDrawerTitle',
        'vueExport': 'LiquidGlassDrawerTitle',
        'wcExport': 'LiquidGlassDrawerTitleElement',
        'elementName': 'proto-ui-liquid-glass-drawer-title',
      },
      {
        'prototypeImport': 'drawerDescription',
        'reactExport': 'LiquidGlassDrawerDescription',
        'vueExport': 'LiquidGlassDrawerDescription',
        'wcExport': 'LiquidGlassDrawerDescriptionElement',
        'elementName': 'proto-ui-liquid-glass-drawer-description',
      },
      {
        'prototypeImport': 'drawerClose',
        'reactExport': 'LiquidGlassDrawerClose',
        'vueExport': 'LiquidGlassDrawerClose',
        'wcExport': 'LiquidGlassDrawerCloseElement',
        'elementName': 'proto-ui-liquid-glass-drawer-close',
      },
      {
        'prototypeImport': 'drawerMask',
        'reactExport': 'LiquidGlassDrawerMask',
        'vueExport': 'LiquidGlassDrawerMask',
        'wcExport': 'LiquidGlassDrawerMaskElement',
        'elementName': 'proto-ui-liquid-glass-drawer-mask',
      },
    ],
  },
  'base-popover': {
    'id': 'base-popover',
    'label': 'Base Popover (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/popover',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'popoverRoot',
        'reactExport': 'BasePopoverRoot',
        'vueExport': 'BasePopoverRoot',
        'wcExport': 'BasePopoverRootElement',
        'elementName': 'proto-ui-base-popover-root',
      },
      {
        'prototypeImport': 'popoverTrigger',
        'reactExport': 'BasePopoverTrigger',
        'vueExport': 'BasePopoverTrigger',
        'wcExport': 'BasePopoverTriggerElement',
        'elementName': 'proto-ui-base-popover-trigger',
      },
      {
        'prototypeImport': 'popoverContent',
        'reactExport': 'BasePopoverContent',
        'vueExport': 'BasePopoverContent',
        'wcExport': 'BasePopoverContentElement',
        'elementName': 'proto-ui-base-popover-content',
      },
      {
        'prototypeImport': 'popoverTitle',
        'reactExport': 'BasePopoverTitle',
        'vueExport': 'BasePopoverTitle',
        'wcExport': 'BasePopoverTitleElement',
        'elementName': 'proto-ui-base-popover-title',
      },
      {
        'prototypeImport': 'popoverDescription',
        'reactExport': 'BasePopoverDescription',
        'vueExport': 'BasePopoverDescription',
        'wcExport': 'BasePopoverDescriptionElement',
        'elementName': 'proto-ui-base-popover-description',
      },
      {
        'prototypeImport': 'popoverClose',
        'reactExport': 'BasePopoverClose',
        'vueExport': 'BasePopoverClose',
        'wcExport': 'BasePopoverCloseElement',
        'elementName': 'proto-ui-base-popover-close',
      },
    ],
  },
  'shadcn-popover': {
    'id': 'shadcn-popover',
    'label': 'Shadcn Popover (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/popover',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'popoverRoot',
        'reactExport': 'ShadcnPopoverRoot',
        'vueExport': 'ShadcnPopoverRoot',
        'wcExport': 'ShadcnPopoverRootElement',
        'elementName': 'proto-ui-shadcn-popover-root',
      },
      {
        'prototypeImport': 'popoverTrigger',
        'reactExport': 'ShadcnPopoverTrigger',
        'vueExport': 'ShadcnPopoverTrigger',
        'wcExport': 'ShadcnPopoverTriggerElement',
        'elementName': 'proto-ui-shadcn-popover-trigger',
      },
      {
        'prototypeImport': 'popoverContent',
        'reactExport': 'ShadcnPopoverContent',
        'vueExport': 'ShadcnPopoverContent',
        'wcExport': 'ShadcnPopoverContentElement',
        'elementName': 'proto-ui-shadcn-popover-content',
      },
      {
        'prototypeImport': 'popoverTitle',
        'reactExport': 'ShadcnPopoverTitle',
        'vueExport': 'ShadcnPopoverTitle',
        'wcExport': 'ShadcnPopoverTitleElement',
        'elementName': 'proto-ui-shadcn-popover-title',
      },
      {
        'prototypeImport': 'popoverDescription',
        'reactExport': 'ShadcnPopoverDescription',
        'vueExport': 'ShadcnPopoverDescription',
        'wcExport': 'ShadcnPopoverDescriptionElement',
        'elementName': 'proto-ui-shadcn-popover-description',
      },
      {
        'prototypeImport': 'popoverClose',
        'reactExport': 'ShadcnPopoverClose',
        'vueExport': 'ShadcnPopoverClose',
        'wcExport': 'ShadcnPopoverCloseElement',
        'elementName': 'proto-ui-shadcn-popover-close',
      },
    ],
  },
  'brutalist-popover': {
    'id': 'brutalist-popover',
    'label': 'Brutalist Popover (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/popover',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'popoverRoot',
        'reactExport': 'BrutalistPopoverRoot',
        'vueExport': 'BrutalistPopoverRoot',
        'wcExport': 'BrutalistPopoverRootElement',
        'elementName': 'proto-ui-brutalist-popover-root',
      },
      {
        'prototypeImport': 'popoverTrigger',
        'reactExport': 'BrutalistPopoverTrigger',
        'vueExport': 'BrutalistPopoverTrigger',
        'wcExport': 'BrutalistPopoverTriggerElement',
        'elementName': 'proto-ui-brutalist-popover-trigger',
      },
      {
        'prototypeImport': 'popoverContent',
        'reactExport': 'BrutalistPopoverContent',
        'vueExport': 'BrutalistPopoverContent',
        'wcExport': 'BrutalistPopoverContentElement',
        'elementName': 'proto-ui-brutalist-popover-content',
      },
      {
        'prototypeImport': 'popoverTitle',
        'reactExport': 'BrutalistPopoverTitle',
        'vueExport': 'BrutalistPopoverTitle',
        'wcExport': 'BrutalistPopoverTitleElement',
        'elementName': 'proto-ui-brutalist-popover-title',
      },
      {
        'prototypeImport': 'popoverDescription',
        'reactExport': 'BrutalistPopoverDescription',
        'vueExport': 'BrutalistPopoverDescription',
        'wcExport': 'BrutalistPopoverDescriptionElement',
        'elementName': 'proto-ui-brutalist-popover-description',
      },
      {
        'prototypeImport': 'popoverClose',
        'reactExport': 'BrutalistPopoverClose',
        'vueExport': 'BrutalistPopoverClose',
        'wcExport': 'BrutalistPopoverCloseElement',
        'elementName': 'proto-ui-brutalist-popover-close',
      },
    ],
  },
  'bootstrap-2-3-2-popover': {
    'id': 'bootstrap-2-3-2-popover',
    'label': 'Bootstrap232 Popover (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/popover',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'popoverRoot',
        'reactExport': 'Bootstrap232PopoverRoot',
        'vueExport': 'Bootstrap232PopoverRoot',
        'wcExport': 'Bootstrap232PopoverRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-popover-root',
      },
      {
        'prototypeImport': 'popoverTrigger',
        'reactExport': 'Bootstrap232PopoverTrigger',
        'vueExport': 'Bootstrap232PopoverTrigger',
        'wcExport': 'Bootstrap232PopoverTriggerElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-popover-trigger',
      },
      {
        'prototypeImport': 'popoverContent',
        'reactExport': 'Bootstrap232PopoverContent',
        'vueExport': 'Bootstrap232PopoverContent',
        'wcExport': 'Bootstrap232PopoverContentElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-popover-content',
      },
      {
        'prototypeImport': 'popoverTitle',
        'reactExport': 'Bootstrap232PopoverTitle',
        'vueExport': 'Bootstrap232PopoverTitle',
        'wcExport': 'Bootstrap232PopoverTitleElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-popover-title',
      },
      {
        'prototypeImport': 'popoverDescription',
        'reactExport': 'Bootstrap232PopoverDescription',
        'vueExport': 'Bootstrap232PopoverDescription',
        'wcExport': 'Bootstrap232PopoverDescriptionElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-popover-description',
      },
      {
        'prototypeImport': 'popoverClose',
        'reactExport': 'Bootstrap232PopoverClose',
        'vueExport': 'Bootstrap232PopoverClose',
        'wcExport': 'Bootstrap232PopoverCloseElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-popover-close',
      },
    ],
  },
  'liquid-glass-popover': {
    'id': 'liquid-glass-popover',
    'label': 'LiquidGlass Popover (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/popover',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'popoverRoot',
        'reactExport': 'LiquidGlassPopoverRoot',
        'vueExport': 'LiquidGlassPopoverRoot',
        'wcExport': 'LiquidGlassPopoverRootElement',
        'elementName': 'proto-ui-liquid-glass-popover-root',
      },
      {
        'prototypeImport': 'popoverTrigger',
        'reactExport': 'LiquidGlassPopoverTrigger',
        'vueExport': 'LiquidGlassPopoverTrigger',
        'wcExport': 'LiquidGlassPopoverTriggerElement',
        'elementName': 'proto-ui-liquid-glass-popover-trigger',
      },
      {
        'prototypeImport': 'popoverContent',
        'reactExport': 'LiquidGlassPopoverContent',
        'vueExport': 'LiquidGlassPopoverContent',
        'wcExport': 'LiquidGlassPopoverContentElement',
        'elementName': 'proto-ui-liquid-glass-popover-content',
      },
      {
        'prototypeImport': 'popoverTitle',
        'reactExport': 'LiquidGlassPopoverTitle',
        'vueExport': 'LiquidGlassPopoverTitle',
        'wcExport': 'LiquidGlassPopoverTitleElement',
        'elementName': 'proto-ui-liquid-glass-popover-title',
      },
      {
        'prototypeImport': 'popoverDescription',
        'reactExport': 'LiquidGlassPopoverDescription',
        'vueExport': 'LiquidGlassPopoverDescription',
        'wcExport': 'LiquidGlassPopoverDescriptionElement',
        'elementName': 'proto-ui-liquid-glass-popover-description',
      },
      {
        'prototypeImport': 'popoverClose',
        'reactExport': 'LiquidGlassPopoverClose',
        'vueExport': 'LiquidGlassPopoverClose',
        'wcExport': 'LiquidGlassPopoverCloseElement',
        'elementName': 'proto-ui-liquid-glass-popover-close',
      },
    ],
  },
  'base-toggle-group': {
    'id': 'base-toggle-group',
    'label': 'Base ToggleGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/toggle-group',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toggleGroupRoot',
        'reactExport': 'BaseToggleGroupRoot',
        'vueExport': 'BaseToggleGroupRoot',
        'wcExport': 'BaseToggleGroupRootElement',
        'elementName': 'proto-ui-base-toggle-group-root',
      },
      {
        'prototypeImport': 'toggleGroupItem',
        'reactExport': 'BaseToggleGroupItem',
        'vueExport': 'BaseToggleGroupItem',
        'wcExport': 'BaseToggleGroupItemElement',
        'elementName': 'proto-ui-base-toggle-group-item',
      },
    ],
  },
  'shadcn-toggle-group': {
    'id': 'shadcn-toggle-group',
    'label': 'Shadcn ToggleGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/toggle-group',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toggleGroupRoot',
        'reactExport': 'ShadcnToggleGroupRoot',
        'vueExport': 'ShadcnToggleGroupRoot',
        'wcExport': 'ShadcnToggleGroupRootElement',
        'elementName': 'proto-ui-shadcn-toggle-group-root',
      },
      {
        'prototypeImport': 'toggleGroupItem',
        'reactExport': 'ShadcnToggleGroupItem',
        'vueExport': 'ShadcnToggleGroupItem',
        'wcExport': 'ShadcnToggleGroupItemElement',
        'elementName': 'proto-ui-shadcn-toggle-group-item',
      },
    ],
  },
  'brutalist-toggle-group': {
    'id': 'brutalist-toggle-group',
    'label': 'Brutalist ToggleGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/toggle-group',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toggleGroupRoot',
        'reactExport': 'BrutalistToggleGroupRoot',
        'vueExport': 'BrutalistToggleGroupRoot',
        'wcExport': 'BrutalistToggleGroupRootElement',
        'elementName': 'proto-ui-brutalist-toggle-group-root',
      },
      {
        'prototypeImport': 'toggleGroupItem',
        'reactExport': 'BrutalistToggleGroupItem',
        'vueExport': 'BrutalistToggleGroupItem',
        'wcExport': 'BrutalistToggleGroupItemElement',
        'elementName': 'proto-ui-brutalist-toggle-group-item',
      },
    ],
  },
  'bootstrap-2-3-2-toggle-group': {
    'id': 'bootstrap-2-3-2-toggle-group',
    'label': 'Bootstrap232 ToggleGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/toggle-group',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toggleGroupRoot',
        'reactExport': 'Bootstrap232ToggleGroupRoot',
        'vueExport': 'Bootstrap232ToggleGroupRoot',
        'wcExport': 'Bootstrap232ToggleGroupRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toggle-group-root',
      },
      {
        'prototypeImport': 'toggleGroupItem',
        'reactExport': 'Bootstrap232ToggleGroupItem',
        'vueExport': 'Bootstrap232ToggleGroupItem',
        'wcExport': 'Bootstrap232ToggleGroupItemElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toggle-group-item',
      },
    ],
  },
  'liquid-glass-toggle-group': {
    'id': 'liquid-glass-toggle-group',
    'label': 'LiquidGlass ToggleGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/toggle-group',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toggleGroupRoot',
        'reactExport': 'LiquidGlassToggleGroupRoot',
        'vueExport': 'LiquidGlassToggleGroupRoot',
        'wcExport': 'LiquidGlassToggleGroupRootElement',
        'elementName': 'proto-ui-liquid-glass-toggle-group-root',
      },
      {
        'prototypeImport': 'toggleGroupItem',
        'reactExport': 'LiquidGlassToggleGroupItem',
        'vueExport': 'LiquidGlassToggleGroupItem',
        'wcExport': 'LiquidGlassToggleGroupItemElement',
        'elementName': 'proto-ui-liquid-glass-toggle-group-item',
      },
    ],
  },
  'base-toolbar': {
    'id': 'base-toolbar',
    'label': 'Base Toolbar (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/toolbar',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toolbarRoot',
        'reactExport': 'BaseToolbarRoot',
        'vueExport': 'BaseToolbarRoot',
        'wcExport': 'BaseToolbarRootElement',
        'elementName': 'proto-ui-base-toolbar-root',
      },
      {
        'prototypeImport': 'toolbarButton',
        'reactExport': 'BaseToolbarButton',
        'vueExport': 'BaseToolbarButton',
        'wcExport': 'BaseToolbarButtonElement',
        'elementName': 'proto-ui-base-toolbar-button',
      },
      {
        'prototypeImport': 'toolbarSeparator',
        'reactExport': 'BaseToolbarSeparator',
        'vueExport': 'BaseToolbarSeparator',
        'wcExport': 'BaseToolbarSeparatorElement',
        'elementName': 'proto-ui-base-toolbar-separator',
      },
    ],
  },
  'shadcn-toolbar': {
    'id': 'shadcn-toolbar',
    'label': 'Shadcn Toolbar (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/toolbar',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toolbarRoot',
        'reactExport': 'ShadcnToolbarRoot',
        'vueExport': 'ShadcnToolbarRoot',
        'wcExport': 'ShadcnToolbarRootElement',
        'elementName': 'proto-ui-shadcn-toolbar-root',
      },
      {
        'prototypeImport': 'toolbarButton',
        'reactExport': 'ShadcnToolbarButton',
        'vueExport': 'ShadcnToolbarButton',
        'wcExport': 'ShadcnToolbarButtonElement',
        'elementName': 'proto-ui-shadcn-toolbar-button',
      },
      {
        'prototypeImport': 'toolbarSeparator',
        'reactExport': 'ShadcnToolbarSeparator',
        'vueExport': 'ShadcnToolbarSeparator',
        'wcExport': 'ShadcnToolbarSeparatorElement',
        'elementName': 'proto-ui-shadcn-toolbar-separator',
      },
    ],
  },
  'brutalist-toolbar': {
    'id': 'brutalist-toolbar',
    'label': 'Brutalist Toolbar (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/toolbar',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toolbarRoot',
        'reactExport': 'BrutalistToolbarRoot',
        'vueExport': 'BrutalistToolbarRoot',
        'wcExport': 'BrutalistToolbarRootElement',
        'elementName': 'proto-ui-brutalist-toolbar-root',
      },
      {
        'prototypeImport': 'toolbarButton',
        'reactExport': 'BrutalistToolbarButton',
        'vueExport': 'BrutalistToolbarButton',
        'wcExport': 'BrutalistToolbarButtonElement',
        'elementName': 'proto-ui-brutalist-toolbar-button',
      },
      {
        'prototypeImport': 'toolbarSeparator',
        'reactExport': 'BrutalistToolbarSeparator',
        'vueExport': 'BrutalistToolbarSeparator',
        'wcExport': 'BrutalistToolbarSeparatorElement',
        'elementName': 'proto-ui-brutalist-toolbar-separator',
      },
    ],
  },
  'bootstrap-2-3-2-toolbar': {
    'id': 'bootstrap-2-3-2-toolbar',
    'label': 'Bootstrap232 Toolbar (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/toolbar',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toolbarRoot',
        'reactExport': 'Bootstrap232ToolbarRoot',
        'vueExport': 'Bootstrap232ToolbarRoot',
        'wcExport': 'Bootstrap232ToolbarRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toolbar-root',
      },
      {
        'prototypeImport': 'toolbarButton',
        'reactExport': 'Bootstrap232ToolbarButton',
        'vueExport': 'Bootstrap232ToolbarButton',
        'wcExport': 'Bootstrap232ToolbarButtonElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toolbar-button',
      },
      {
        'prototypeImport': 'toolbarSeparator',
        'reactExport': 'Bootstrap232ToolbarSeparator',
        'vueExport': 'Bootstrap232ToolbarSeparator',
        'wcExport': 'Bootstrap232ToolbarSeparatorElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toolbar-separator',
      },
    ],
  },
  'liquid-glass-toolbar': {
    'id': 'liquid-glass-toolbar',
    'label': 'LiquidGlass Toolbar (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/toolbar',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toolbarRoot',
        'reactExport': 'LiquidGlassToolbarRoot',
        'vueExport': 'LiquidGlassToolbarRoot',
        'wcExport': 'LiquidGlassToolbarRootElement',
        'elementName': 'proto-ui-liquid-glass-toolbar-root',
      },
      {
        'prototypeImport': 'toolbarButton',
        'reactExport': 'LiquidGlassToolbarButton',
        'vueExport': 'LiquidGlassToolbarButton',
        'wcExport': 'LiquidGlassToolbarButtonElement',
        'elementName': 'proto-ui-liquid-glass-toolbar-button',
      },
      {
        'prototypeImport': 'toolbarSeparator',
        'reactExport': 'LiquidGlassToolbarSeparator',
        'vueExport': 'LiquidGlassToolbarSeparator',
        'wcExport': 'LiquidGlassToolbarSeparatorElement',
        'elementName': 'proto-ui-liquid-glass-toolbar-separator',
      },
    ],
  },
  'base-toast': {
    'id': 'base-toast',
    'label': 'Base Toast (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/toast',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toastRoot',
        'reactExport': 'BaseToastRoot',
        'vueExport': 'BaseToastRoot',
        'wcExport': 'BaseToastRootElement',
        'elementName': 'proto-ui-base-toast-root',
      },
      {
        'prototypeImport': 'toastViewport',
        'reactExport': 'BaseToastViewport',
        'vueExport': 'BaseToastViewport',
        'wcExport': 'BaseToastViewportElement',
        'elementName': 'proto-ui-base-toast-viewport',
      },
      {
        'prototypeImport': 'toastTitle',
        'reactExport': 'BaseToastTitle',
        'vueExport': 'BaseToastTitle',
        'wcExport': 'BaseToastTitleElement',
        'elementName': 'proto-ui-base-toast-title',
      },
      {
        'prototypeImport': 'toastDescription',
        'reactExport': 'BaseToastDescription',
        'vueExport': 'BaseToastDescription',
        'wcExport': 'BaseToastDescriptionElement',
        'elementName': 'proto-ui-base-toast-description',
      },
      {
        'prototypeImport': 'toastAction',
        'reactExport': 'BaseToastAction',
        'vueExport': 'BaseToastAction',
        'wcExport': 'BaseToastActionElement',
        'elementName': 'proto-ui-base-toast-action',
      },
      {
        'prototypeImport': 'toastClose',
        'reactExport': 'BaseToastClose',
        'vueExport': 'BaseToastClose',
        'wcExport': 'BaseToastCloseElement',
        'elementName': 'proto-ui-base-toast-close',
      },
    ],
  },
  'shadcn-toast': {
    'id': 'shadcn-toast',
    'label': 'Shadcn Toast (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/toast',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toastRoot',
        'reactExport': 'ShadcnToastRoot',
        'vueExport': 'ShadcnToastRoot',
        'wcExport': 'ShadcnToastRootElement',
        'elementName': 'proto-ui-shadcn-toast-root',
      },
      {
        'prototypeImport': 'toastViewport',
        'reactExport': 'ShadcnToastViewport',
        'vueExport': 'ShadcnToastViewport',
        'wcExport': 'ShadcnToastViewportElement',
        'elementName': 'proto-ui-shadcn-toast-viewport',
      },
      {
        'prototypeImport': 'toastTitle',
        'reactExport': 'ShadcnToastTitle',
        'vueExport': 'ShadcnToastTitle',
        'wcExport': 'ShadcnToastTitleElement',
        'elementName': 'proto-ui-shadcn-toast-title',
      },
      {
        'prototypeImport': 'toastDescription',
        'reactExport': 'ShadcnToastDescription',
        'vueExport': 'ShadcnToastDescription',
        'wcExport': 'ShadcnToastDescriptionElement',
        'elementName': 'proto-ui-shadcn-toast-description',
      },
      {
        'prototypeImport': 'toastAction',
        'reactExport': 'ShadcnToastAction',
        'vueExport': 'ShadcnToastAction',
        'wcExport': 'ShadcnToastActionElement',
        'elementName': 'proto-ui-shadcn-toast-action',
      },
      {
        'prototypeImport': 'toastClose',
        'reactExport': 'ShadcnToastClose',
        'vueExport': 'ShadcnToastClose',
        'wcExport': 'ShadcnToastCloseElement',
        'elementName': 'proto-ui-shadcn-toast-close',
      },
    ],
  },
  'brutalist-toast': {
    'id': 'brutalist-toast',
    'label': 'Brutalist Toast (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/toast',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toastRoot',
        'reactExport': 'BrutalistToastRoot',
        'vueExport': 'BrutalistToastRoot',
        'wcExport': 'BrutalistToastRootElement',
        'elementName': 'proto-ui-brutalist-toast-root',
      },
      {
        'prototypeImport': 'toastViewport',
        'reactExport': 'BrutalistToastViewport',
        'vueExport': 'BrutalistToastViewport',
        'wcExport': 'BrutalistToastViewportElement',
        'elementName': 'proto-ui-brutalist-toast-viewport',
      },
      {
        'prototypeImport': 'toastTitle',
        'reactExport': 'BrutalistToastTitle',
        'vueExport': 'BrutalistToastTitle',
        'wcExport': 'BrutalistToastTitleElement',
        'elementName': 'proto-ui-brutalist-toast-title',
      },
      {
        'prototypeImport': 'toastDescription',
        'reactExport': 'BrutalistToastDescription',
        'vueExport': 'BrutalistToastDescription',
        'wcExport': 'BrutalistToastDescriptionElement',
        'elementName': 'proto-ui-brutalist-toast-description',
      },
      {
        'prototypeImport': 'toastAction',
        'reactExport': 'BrutalistToastAction',
        'vueExport': 'BrutalistToastAction',
        'wcExport': 'BrutalistToastActionElement',
        'elementName': 'proto-ui-brutalist-toast-action',
      },
      {
        'prototypeImport': 'toastClose',
        'reactExport': 'BrutalistToastClose',
        'vueExport': 'BrutalistToastClose',
        'wcExport': 'BrutalistToastCloseElement',
        'elementName': 'proto-ui-brutalist-toast-close',
      },
    ],
  },
  'bootstrap-2-3-2-toast': {
    'id': 'bootstrap-2-3-2-toast',
    'label': 'Bootstrap232 Toast (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/toast',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toastRoot',
        'reactExport': 'Bootstrap232ToastRoot',
        'vueExport': 'Bootstrap232ToastRoot',
        'wcExport': 'Bootstrap232ToastRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toast-root',
      },
      {
        'prototypeImport': 'toastViewport',
        'reactExport': 'Bootstrap232ToastViewport',
        'vueExport': 'Bootstrap232ToastViewport',
        'wcExport': 'Bootstrap232ToastViewportElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toast-viewport',
      },
      {
        'prototypeImport': 'toastTitle',
        'reactExport': 'Bootstrap232ToastTitle',
        'vueExport': 'Bootstrap232ToastTitle',
        'wcExport': 'Bootstrap232ToastTitleElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toast-title',
      },
      {
        'prototypeImport': 'toastDescription',
        'reactExport': 'Bootstrap232ToastDescription',
        'vueExport': 'Bootstrap232ToastDescription',
        'wcExport': 'Bootstrap232ToastDescriptionElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toast-description',
      },
      {
        'prototypeImport': 'toastAction',
        'reactExport': 'Bootstrap232ToastAction',
        'vueExport': 'Bootstrap232ToastAction',
        'wcExport': 'Bootstrap232ToastActionElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toast-action',
      },
      {
        'prototypeImport': 'toastClose',
        'reactExport': 'Bootstrap232ToastClose',
        'vueExport': 'Bootstrap232ToastClose',
        'wcExport': 'Bootstrap232ToastCloseElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-toast-close',
      },
    ],
  },
  'liquid-glass-toast': {
    'id': 'liquid-glass-toast',
    'label': 'LiquidGlass Toast (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/toast',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'toastRoot',
        'reactExport': 'LiquidGlassToastRoot',
        'vueExport': 'LiquidGlassToastRoot',
        'wcExport': 'LiquidGlassToastRootElement',
        'elementName': 'proto-ui-liquid-glass-toast-root',
      },
      {
        'prototypeImport': 'toastViewport',
        'reactExport': 'LiquidGlassToastViewport',
        'vueExport': 'LiquidGlassToastViewport',
        'wcExport': 'LiquidGlassToastViewportElement',
        'elementName': 'proto-ui-liquid-glass-toast-viewport',
      },
      {
        'prototypeImport': 'toastTitle',
        'reactExport': 'LiquidGlassToastTitle',
        'vueExport': 'LiquidGlassToastTitle',
        'wcExport': 'LiquidGlassToastTitleElement',
        'elementName': 'proto-ui-liquid-glass-toast-title',
      },
      {
        'prototypeImport': 'toastDescription',
        'reactExport': 'LiquidGlassToastDescription',
        'vueExport': 'LiquidGlassToastDescription',
        'wcExport': 'LiquidGlassToastDescriptionElement',
        'elementName': 'proto-ui-liquid-glass-toast-description',
      },
      {
        'prototypeImport': 'toastAction',
        'reactExport': 'LiquidGlassToastAction',
        'vueExport': 'LiquidGlassToastAction',
        'wcExport': 'LiquidGlassToastActionElement',
        'elementName': 'proto-ui-liquid-glass-toast-action',
      },
      {
        'prototypeImport': 'toastClose',
        'reactExport': 'LiquidGlassToastClose',
        'vueExport': 'LiquidGlassToastClose',
        'wcExport': 'LiquidGlassToastCloseElement',
        'elementName': 'proto-ui-liquid-glass-toast-close',
      },
    ],
  },
  'base-progress': {
    'id': 'base-progress',
    'label': 'Base Progress (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/progress',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'progressRoot',
        'reactExport': 'BaseProgressRoot',
        'vueExport': 'BaseProgressRoot',
        'wcExport': 'BaseProgressRootElement',
        'elementName': 'proto-ui-base-progress-root',
      },
      {
        'prototypeImport': 'progressLabel',
        'reactExport': 'BaseProgressLabel',
        'vueExport': 'BaseProgressLabel',
        'wcExport': 'BaseProgressLabelElement',
        'elementName': 'proto-ui-base-progress-label',
      },
      {
        'prototypeImport': 'progressTrack',
        'reactExport': 'BaseProgressTrack',
        'vueExport': 'BaseProgressTrack',
        'wcExport': 'BaseProgressTrackElement',
        'elementName': 'proto-ui-base-progress-track',
      },
      {
        'prototypeImport': 'progressIndicator',
        'reactExport': 'BaseProgressIndicator',
        'vueExport': 'BaseProgressIndicator',
        'wcExport': 'BaseProgressIndicatorElement',
        'elementName': 'proto-ui-base-progress-indicator',
      },
      {
        'prototypeImport': 'progressValue',
        'reactExport': 'BaseProgressValue',
        'vueExport': 'BaseProgressValue',
        'wcExport': 'BaseProgressValueElement',
        'elementName': 'proto-ui-base-progress-value',
      },
    ],
  },
  'base-meter': {
    'id': 'base-meter',
    'label': 'Base Meter (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/meter',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'meterRoot',
        'reactExport': 'BaseMeterRoot',
        'vueExport': 'BaseMeterRoot',
        'wcExport': 'BaseMeterRootElement',
        'elementName': 'proto-ui-base-meter-root',
      },
      {
        'prototypeImport': 'meterLabel',
        'reactExport': 'BaseMeterLabel',
        'vueExport': 'BaseMeterLabel',
        'wcExport': 'BaseMeterLabelElement',
        'elementName': 'proto-ui-base-meter-label',
      },
      {
        'prototypeImport': 'meterTrack',
        'reactExport': 'BaseMeterTrack',
        'vueExport': 'BaseMeterTrack',
        'wcExport': 'BaseMeterTrackElement',
        'elementName': 'proto-ui-base-meter-track',
      },
      {
        'prototypeImport': 'meterIndicator',
        'reactExport': 'BaseMeterIndicator',
        'vueExport': 'BaseMeterIndicator',
        'wcExport': 'BaseMeterIndicatorElement',
        'elementName': 'proto-ui-base-meter-indicator',
      },
      {
        'prototypeImport': 'meterValue',
        'reactExport': 'BaseMeterValue',
        'vueExport': 'BaseMeterValue',
        'wcExport': 'BaseMeterValueElement',
        'elementName': 'proto-ui-base-meter-value',
      },
    ],
  },
  'base-fieldset': {
    'id': 'base-fieldset',
    'label': 'Base Fieldset (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/fieldset',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'fieldsetRoot',
        'reactExport': 'BaseFieldsetRoot',
        'vueExport': 'BaseFieldsetRoot',
        'wcExport': 'BaseFieldsetRootElement',
        'elementName': 'proto-ui-base-fieldset-root',
      },
      {
        'prototypeImport': 'fieldsetLegend',
        'reactExport': 'BaseFieldsetLegend',
        'vueExport': 'BaseFieldsetLegend',
        'wcExport': 'BaseFieldsetLegendElement',
        'elementName': 'proto-ui-base-fieldset-legend',
      },
      {
        'prototypeImport': 'fieldsetDescription',
        'reactExport': 'BaseFieldsetDescription',
        'vueExport': 'BaseFieldsetDescription',
        'wcExport': 'BaseFieldsetDescriptionElement',
        'elementName': 'proto-ui-base-fieldset-description',
      },
    ],
  },
  'base-form': {
    'id': 'base-form',
    'label': 'Base Form (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/form',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'formRoot',
        'reactExport': 'BaseFormRoot',
        'vueExport': 'BaseFormRoot',
        'wcExport': 'BaseFormRootElement',
        'elementName': 'proto-ui-base-form-root',
      },
      {
        'prototypeImport': 'formField',
        'reactExport': 'BaseFormField',
        'vueExport': 'BaseFormField',
        'wcExport': 'BaseFormFieldElement',
        'elementName': 'proto-ui-base-form-field',
      },
      {
        'prototypeImport': 'formSubmit',
        'reactExport': 'BaseFormSubmit',
        'vueExport': 'BaseFormSubmit',
        'wcExport': 'BaseFormSubmitElement',
        'elementName': 'proto-ui-base-form-submit',
      },
    ],
  },
  'base-checkbox-group': {
    'id': 'base-checkbox-group',
    'label': 'Base CheckboxGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/checkbox-group',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'checkboxGroupRoot',
        'reactExport': 'BaseCheckboxGroupRoot',
        'vueExport': 'BaseCheckboxGroupRoot',
        'wcExport': 'BaseCheckboxGroupRootElement',
        'elementName': 'proto-ui-base-checkbox-group-root',
      },
      {
        'prototypeImport': 'checkboxGroupItem',
        'reactExport': 'BaseCheckboxGroupItem',
        'vueExport': 'BaseCheckboxGroupItem',
        'wcExport': 'BaseCheckboxGroupItemElement',
        'elementName': 'proto-ui-base-checkbox-group-item',
      },
      {
        'prototypeImport': 'checkboxGroupAll',
        'reactExport': 'BaseCheckboxGroupAll',
        'vueExport': 'BaseCheckboxGroupAll',
        'wcExport': 'BaseCheckboxGroupAllElement',
        'elementName': 'proto-ui-base-checkbox-group-all',
      },
    ],
  },
  'shadcn-progress': {
    'id': 'shadcn-progress',
    'label': 'Shadcn Progress (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/progress',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'progressRoot',
        'reactExport': 'ShadcnProgressRoot',
        'vueExport': 'ShadcnProgressRoot',
        'wcExport': 'ShadcnProgressRootElement',
        'elementName': 'proto-ui-shadcn-progress-root',
      },
      {
        'prototypeImport': 'progressLabel',
        'reactExport': 'ShadcnProgressLabel',
        'vueExport': 'ShadcnProgressLabel',
        'wcExport': 'ShadcnProgressLabelElement',
        'elementName': 'proto-ui-shadcn-progress-label',
      },
      {
        'prototypeImport': 'progressTrack',
        'reactExport': 'ShadcnProgressTrack',
        'vueExport': 'ShadcnProgressTrack',
        'wcExport': 'ShadcnProgressTrackElement',
        'elementName': 'proto-ui-shadcn-progress-track',
      },
      {
        'prototypeImport': 'progressIndicator',
        'reactExport': 'ShadcnProgressIndicator',
        'vueExport': 'ShadcnProgressIndicator',
        'wcExport': 'ShadcnProgressIndicatorElement',
        'elementName': 'proto-ui-shadcn-progress-indicator',
      },
      {
        'prototypeImport': 'progressValue',
        'reactExport': 'ShadcnProgressValue',
        'vueExport': 'ShadcnProgressValue',
        'wcExport': 'ShadcnProgressValueElement',
        'elementName': 'proto-ui-shadcn-progress-value',
      },
    ],
  },
  'shadcn-meter': {
    'id': 'shadcn-meter',
    'label': 'Shadcn Meter (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/meter',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'meterRoot',
        'reactExport': 'ShadcnMeterRoot',
        'vueExport': 'ShadcnMeterRoot',
        'wcExport': 'ShadcnMeterRootElement',
        'elementName': 'proto-ui-shadcn-meter-root',
      },
      {
        'prototypeImport': 'meterLabel',
        'reactExport': 'ShadcnMeterLabel',
        'vueExport': 'ShadcnMeterLabel',
        'wcExport': 'ShadcnMeterLabelElement',
        'elementName': 'proto-ui-shadcn-meter-label',
      },
      {
        'prototypeImport': 'meterTrack',
        'reactExport': 'ShadcnMeterTrack',
        'vueExport': 'ShadcnMeterTrack',
        'wcExport': 'ShadcnMeterTrackElement',
        'elementName': 'proto-ui-shadcn-meter-track',
      },
      {
        'prototypeImport': 'meterIndicator',
        'reactExport': 'ShadcnMeterIndicator',
        'vueExport': 'ShadcnMeterIndicator',
        'wcExport': 'ShadcnMeterIndicatorElement',
        'elementName': 'proto-ui-shadcn-meter-indicator',
      },
      {
        'prototypeImport': 'meterValue',
        'reactExport': 'ShadcnMeterValue',
        'vueExport': 'ShadcnMeterValue',
        'wcExport': 'ShadcnMeterValueElement',
        'elementName': 'proto-ui-shadcn-meter-value',
      },
    ],
  },
  'shadcn-fieldset': {
    'id': 'shadcn-fieldset',
    'label': 'Shadcn Fieldset (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/fieldset',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'fieldsetRoot',
        'reactExport': 'ShadcnFieldsetRoot',
        'vueExport': 'ShadcnFieldsetRoot',
        'wcExport': 'ShadcnFieldsetRootElement',
        'elementName': 'proto-ui-shadcn-fieldset-root',
      },
      {
        'prototypeImport': 'fieldsetLegend',
        'reactExport': 'ShadcnFieldsetLegend',
        'vueExport': 'ShadcnFieldsetLegend',
        'wcExport': 'ShadcnFieldsetLegendElement',
        'elementName': 'proto-ui-shadcn-fieldset-legend',
      },
      {
        'prototypeImport': 'fieldsetDescription',
        'reactExport': 'ShadcnFieldsetDescription',
        'vueExport': 'ShadcnFieldsetDescription',
        'wcExport': 'ShadcnFieldsetDescriptionElement',
        'elementName': 'proto-ui-shadcn-fieldset-description',
      },
    ],
  },
  'shadcn-form': {
    'id': 'shadcn-form',
    'label': 'Shadcn Form (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/form',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'formRoot',
        'reactExport': 'ShadcnFormRoot',
        'vueExport': 'ShadcnFormRoot',
        'wcExport': 'ShadcnFormRootElement',
        'elementName': 'proto-ui-shadcn-form-root',
      },
      {
        'prototypeImport': 'formField',
        'reactExport': 'ShadcnFormField',
        'vueExport': 'ShadcnFormField',
        'wcExport': 'ShadcnFormFieldElement',
        'elementName': 'proto-ui-shadcn-form-field',
      },
      {
        'prototypeImport': 'formSubmit',
        'reactExport': 'ShadcnFormSubmit',
        'vueExport': 'ShadcnFormSubmit',
        'wcExport': 'ShadcnFormSubmitElement',
        'elementName': 'proto-ui-shadcn-form-submit',
      },
    ],
  },
  'shadcn-checkbox-group': {
    'id': 'shadcn-checkbox-group',
    'label': 'Shadcn CheckboxGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/checkbox-group',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'checkboxGroupRoot',
        'reactExport': 'ShadcnCheckboxGroupRoot',
        'vueExport': 'ShadcnCheckboxGroupRoot',
        'wcExport': 'ShadcnCheckboxGroupRootElement',
        'elementName': 'proto-ui-shadcn-checkbox-group-root',
      },
      {
        'prototypeImport': 'checkboxGroupItem',
        'reactExport': 'ShadcnCheckboxGroupItem',
        'vueExport': 'ShadcnCheckboxGroupItem',
        'wcExport': 'ShadcnCheckboxGroupItemElement',
        'elementName': 'proto-ui-shadcn-checkbox-group-item',
      },
      {
        'prototypeImport': 'checkboxGroupAll',
        'reactExport': 'ShadcnCheckboxGroupAll',
        'vueExport': 'ShadcnCheckboxGroupAll',
        'wcExport': 'ShadcnCheckboxGroupAllElement',
        'elementName': 'proto-ui-shadcn-checkbox-group-all',
      },
    ],
  },
  'brutalist-progress': {
    'id': 'brutalist-progress',
    'label': 'Brutalist Progress (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/progress',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'progressRoot',
        'reactExport': 'BrutalistProgressRoot',
        'vueExport': 'BrutalistProgressRoot',
        'wcExport': 'BrutalistProgressRootElement',
        'elementName': 'proto-ui-brutalist-progress-root',
      },
      {
        'prototypeImport': 'progressLabel',
        'reactExport': 'BrutalistProgressLabel',
        'vueExport': 'BrutalistProgressLabel',
        'wcExport': 'BrutalistProgressLabelElement',
        'elementName': 'proto-ui-brutalist-progress-label',
      },
      {
        'prototypeImport': 'progressTrack',
        'reactExport': 'BrutalistProgressTrack',
        'vueExport': 'BrutalistProgressTrack',
        'wcExport': 'BrutalistProgressTrackElement',
        'elementName': 'proto-ui-brutalist-progress-track',
      },
      {
        'prototypeImport': 'progressIndicator',
        'reactExport': 'BrutalistProgressIndicator',
        'vueExport': 'BrutalistProgressIndicator',
        'wcExport': 'BrutalistProgressIndicatorElement',
        'elementName': 'proto-ui-brutalist-progress-indicator',
      },
      {
        'prototypeImport': 'progressValue',
        'reactExport': 'BrutalistProgressValue',
        'vueExport': 'BrutalistProgressValue',
        'wcExport': 'BrutalistProgressValueElement',
        'elementName': 'proto-ui-brutalist-progress-value',
      },
    ],
  },
  'brutalist-meter': {
    'id': 'brutalist-meter',
    'label': 'Brutalist Meter (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/meter',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'meterRoot',
        'reactExport': 'BrutalistMeterRoot',
        'vueExport': 'BrutalistMeterRoot',
        'wcExport': 'BrutalistMeterRootElement',
        'elementName': 'proto-ui-brutalist-meter-root',
      },
      {
        'prototypeImport': 'meterLabel',
        'reactExport': 'BrutalistMeterLabel',
        'vueExport': 'BrutalistMeterLabel',
        'wcExport': 'BrutalistMeterLabelElement',
        'elementName': 'proto-ui-brutalist-meter-label',
      },
      {
        'prototypeImport': 'meterTrack',
        'reactExport': 'BrutalistMeterTrack',
        'vueExport': 'BrutalistMeterTrack',
        'wcExport': 'BrutalistMeterTrackElement',
        'elementName': 'proto-ui-brutalist-meter-track',
      },
      {
        'prototypeImport': 'meterIndicator',
        'reactExport': 'BrutalistMeterIndicator',
        'vueExport': 'BrutalistMeterIndicator',
        'wcExport': 'BrutalistMeterIndicatorElement',
        'elementName': 'proto-ui-brutalist-meter-indicator',
      },
      {
        'prototypeImport': 'meterValue',
        'reactExport': 'BrutalistMeterValue',
        'vueExport': 'BrutalistMeterValue',
        'wcExport': 'BrutalistMeterValueElement',
        'elementName': 'proto-ui-brutalist-meter-value',
      },
    ],
  },
  'brutalist-fieldset': {
    'id': 'brutalist-fieldset',
    'label': 'Brutalist Fieldset (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/fieldset',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'fieldsetRoot',
        'reactExport': 'BrutalistFieldsetRoot',
        'vueExport': 'BrutalistFieldsetRoot',
        'wcExport': 'BrutalistFieldsetRootElement',
        'elementName': 'proto-ui-brutalist-fieldset-root',
      },
      {
        'prototypeImport': 'fieldsetLegend',
        'reactExport': 'BrutalistFieldsetLegend',
        'vueExport': 'BrutalistFieldsetLegend',
        'wcExport': 'BrutalistFieldsetLegendElement',
        'elementName': 'proto-ui-brutalist-fieldset-legend',
      },
      {
        'prototypeImport': 'fieldsetDescription',
        'reactExport': 'BrutalistFieldsetDescription',
        'vueExport': 'BrutalistFieldsetDescription',
        'wcExport': 'BrutalistFieldsetDescriptionElement',
        'elementName': 'proto-ui-brutalist-fieldset-description',
      },
    ],
  },
  'brutalist-form': {
    'id': 'brutalist-form',
    'label': 'Brutalist Form (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/form',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'formRoot',
        'reactExport': 'BrutalistFormRoot',
        'vueExport': 'BrutalistFormRoot',
        'wcExport': 'BrutalistFormRootElement',
        'elementName': 'proto-ui-brutalist-form-root',
      },
      {
        'prototypeImport': 'formField',
        'reactExport': 'BrutalistFormField',
        'vueExport': 'BrutalistFormField',
        'wcExport': 'BrutalistFormFieldElement',
        'elementName': 'proto-ui-brutalist-form-field',
      },
      {
        'prototypeImport': 'formSubmit',
        'reactExport': 'BrutalistFormSubmit',
        'vueExport': 'BrutalistFormSubmit',
        'wcExport': 'BrutalistFormSubmitElement',
        'elementName': 'proto-ui-brutalist-form-submit',
      },
    ],
  },
  'brutalist-checkbox-group': {
    'id': 'brutalist-checkbox-group',
    'label': 'Brutalist CheckboxGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/checkbox-group',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'checkboxGroupRoot',
        'reactExport': 'BrutalistCheckboxGroupRoot',
        'vueExport': 'BrutalistCheckboxGroupRoot',
        'wcExport': 'BrutalistCheckboxGroupRootElement',
        'elementName': 'proto-ui-brutalist-checkbox-group-root',
      },
      {
        'prototypeImport': 'checkboxGroupItem',
        'reactExport': 'BrutalistCheckboxGroupItem',
        'vueExport': 'BrutalistCheckboxGroupItem',
        'wcExport': 'BrutalistCheckboxGroupItemElement',
        'elementName': 'proto-ui-brutalist-checkbox-group-item',
      },
      {
        'prototypeImport': 'checkboxGroupAll',
        'reactExport': 'BrutalistCheckboxGroupAll',
        'vueExport': 'BrutalistCheckboxGroupAll',
        'wcExport': 'BrutalistCheckboxGroupAllElement',
        'elementName': 'proto-ui-brutalist-checkbox-group-all',
      },
    ],
  },
  'bootstrap-2-3-2-progress': {
    'id': 'bootstrap-2-3-2-progress',
    'label': 'Bootstrap232 Progress (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/progress',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'progressRoot',
        'reactExport': 'Bootstrap232ProgressRoot',
        'vueExport': 'Bootstrap232ProgressRoot',
        'wcExport': 'Bootstrap232ProgressRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-progress-root',
      },
      {
        'prototypeImport': 'progressLabel',
        'reactExport': 'Bootstrap232ProgressLabel',
        'vueExport': 'Bootstrap232ProgressLabel',
        'wcExport': 'Bootstrap232ProgressLabelElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-progress-label',
      },
      {
        'prototypeImport': 'progressTrack',
        'reactExport': 'Bootstrap232ProgressTrack',
        'vueExport': 'Bootstrap232ProgressTrack',
        'wcExport': 'Bootstrap232ProgressTrackElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-progress-track',
      },
      {
        'prototypeImport': 'progressIndicator',
        'reactExport': 'Bootstrap232ProgressIndicator',
        'vueExport': 'Bootstrap232ProgressIndicator',
        'wcExport': 'Bootstrap232ProgressIndicatorElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-progress-indicator',
      },
      {
        'prototypeImport': 'progressValue',
        'reactExport': 'Bootstrap232ProgressValue',
        'vueExport': 'Bootstrap232ProgressValue',
        'wcExport': 'Bootstrap232ProgressValueElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-progress-value',
      },
    ],
  },
  'bootstrap-2-3-2-meter': {
    'id': 'bootstrap-2-3-2-meter',
    'label': 'Bootstrap232 Meter (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/meter',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'meterRoot',
        'reactExport': 'Bootstrap232MeterRoot',
        'vueExport': 'Bootstrap232MeterRoot',
        'wcExport': 'Bootstrap232MeterRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-meter-root',
      },
      {
        'prototypeImport': 'meterLabel',
        'reactExport': 'Bootstrap232MeterLabel',
        'vueExport': 'Bootstrap232MeterLabel',
        'wcExport': 'Bootstrap232MeterLabelElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-meter-label',
      },
      {
        'prototypeImport': 'meterTrack',
        'reactExport': 'Bootstrap232MeterTrack',
        'vueExport': 'Bootstrap232MeterTrack',
        'wcExport': 'Bootstrap232MeterTrackElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-meter-track',
      },
      {
        'prototypeImport': 'meterIndicator',
        'reactExport': 'Bootstrap232MeterIndicator',
        'vueExport': 'Bootstrap232MeterIndicator',
        'wcExport': 'Bootstrap232MeterIndicatorElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-meter-indicator',
      },
      {
        'prototypeImport': 'meterValue',
        'reactExport': 'Bootstrap232MeterValue',
        'vueExport': 'Bootstrap232MeterValue',
        'wcExport': 'Bootstrap232MeterValueElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-meter-value',
      },
    ],
  },
  'bootstrap-2-3-2-fieldset': {
    'id': 'bootstrap-2-3-2-fieldset',
    'label': 'Bootstrap232 Fieldset (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/fieldset',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'fieldsetRoot',
        'reactExport': 'Bootstrap232FieldsetRoot',
        'vueExport': 'Bootstrap232FieldsetRoot',
        'wcExport': 'Bootstrap232FieldsetRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-fieldset-root',
      },
      {
        'prototypeImport': 'fieldsetLegend',
        'reactExport': 'Bootstrap232FieldsetLegend',
        'vueExport': 'Bootstrap232FieldsetLegend',
        'wcExport': 'Bootstrap232FieldsetLegendElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-fieldset-legend',
      },
      {
        'prototypeImport': 'fieldsetDescription',
        'reactExport': 'Bootstrap232FieldsetDescription',
        'vueExport': 'Bootstrap232FieldsetDescription',
        'wcExport': 'Bootstrap232FieldsetDescriptionElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-fieldset-description',
      },
    ],
  },
  'bootstrap-2-3-2-form': {
    'id': 'bootstrap-2-3-2-form',
    'label': 'Bootstrap232 Form (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/form',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'formRoot',
        'reactExport': 'Bootstrap232FormRoot',
        'vueExport': 'Bootstrap232FormRoot',
        'wcExport': 'Bootstrap232FormRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-form-root',
      },
      {
        'prototypeImport': 'formField',
        'reactExport': 'Bootstrap232FormField',
        'vueExport': 'Bootstrap232FormField',
        'wcExport': 'Bootstrap232FormFieldElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-form-field',
      },
      {
        'prototypeImport': 'formSubmit',
        'reactExport': 'Bootstrap232FormSubmit',
        'vueExport': 'Bootstrap232FormSubmit',
        'wcExport': 'Bootstrap232FormSubmitElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-form-submit',
      },
    ],
  },
  'bootstrap-2-3-2-checkbox-group': {
    'id': 'bootstrap-2-3-2-checkbox-group',
    'label': 'Bootstrap232 CheckboxGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/checkbox-group',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'checkboxGroupRoot',
        'reactExport': 'Bootstrap232CheckboxGroupRoot',
        'vueExport': 'Bootstrap232CheckboxGroupRoot',
        'wcExport': 'Bootstrap232CheckboxGroupRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-checkbox-group-root',
      },
      {
        'prototypeImport': 'checkboxGroupItem',
        'reactExport': 'Bootstrap232CheckboxGroupItem',
        'vueExport': 'Bootstrap232CheckboxGroupItem',
        'wcExport': 'Bootstrap232CheckboxGroupItemElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-checkbox-group-item',
      },
      {
        'prototypeImport': 'checkboxGroupAll',
        'reactExport': 'Bootstrap232CheckboxGroupAll',
        'vueExport': 'Bootstrap232CheckboxGroupAll',
        'wcExport': 'Bootstrap232CheckboxGroupAllElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-checkbox-group-all',
      },
    ],
  },
  'liquid-glass-progress': {
    'id': 'liquid-glass-progress',
    'label': 'LiquidGlass Progress (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/progress',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'progressRoot',
        'reactExport': 'LiquidGlassProgressRoot',
        'vueExport': 'LiquidGlassProgressRoot',
        'wcExport': 'LiquidGlassProgressRootElement',
        'elementName': 'proto-ui-liquid-glass-progress-root',
      },
      {
        'prototypeImport': 'progressLabel',
        'reactExport': 'LiquidGlassProgressLabel',
        'vueExport': 'LiquidGlassProgressLabel',
        'wcExport': 'LiquidGlassProgressLabelElement',
        'elementName': 'proto-ui-liquid-glass-progress-label',
      },
      {
        'prototypeImport': 'progressTrack',
        'reactExport': 'LiquidGlassProgressTrack',
        'vueExport': 'LiquidGlassProgressTrack',
        'wcExport': 'LiquidGlassProgressTrackElement',
        'elementName': 'proto-ui-liquid-glass-progress-track',
      },
      {
        'prototypeImport': 'progressIndicator',
        'reactExport': 'LiquidGlassProgressIndicator',
        'vueExport': 'LiquidGlassProgressIndicator',
        'wcExport': 'LiquidGlassProgressIndicatorElement',
        'elementName': 'proto-ui-liquid-glass-progress-indicator',
      },
      {
        'prototypeImport': 'progressValue',
        'reactExport': 'LiquidGlassProgressValue',
        'vueExport': 'LiquidGlassProgressValue',
        'wcExport': 'LiquidGlassProgressValueElement',
        'elementName': 'proto-ui-liquid-glass-progress-value',
      },
    ],
  },
  'liquid-glass-meter': {
    'id': 'liquid-glass-meter',
    'label': 'LiquidGlass Meter (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/meter',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'meterRoot',
        'reactExport': 'LiquidGlassMeterRoot',
        'vueExport': 'LiquidGlassMeterRoot',
        'wcExport': 'LiquidGlassMeterRootElement',
        'elementName': 'proto-ui-liquid-glass-meter-root',
      },
      {
        'prototypeImport': 'meterLabel',
        'reactExport': 'LiquidGlassMeterLabel',
        'vueExport': 'LiquidGlassMeterLabel',
        'wcExport': 'LiquidGlassMeterLabelElement',
        'elementName': 'proto-ui-liquid-glass-meter-label',
      },
      {
        'prototypeImport': 'meterTrack',
        'reactExport': 'LiquidGlassMeterTrack',
        'vueExport': 'LiquidGlassMeterTrack',
        'wcExport': 'LiquidGlassMeterTrackElement',
        'elementName': 'proto-ui-liquid-glass-meter-track',
      },
      {
        'prototypeImport': 'meterIndicator',
        'reactExport': 'LiquidGlassMeterIndicator',
        'vueExport': 'LiquidGlassMeterIndicator',
        'wcExport': 'LiquidGlassMeterIndicatorElement',
        'elementName': 'proto-ui-liquid-glass-meter-indicator',
      },
      {
        'prototypeImport': 'meterValue',
        'reactExport': 'LiquidGlassMeterValue',
        'vueExport': 'LiquidGlassMeterValue',
        'wcExport': 'LiquidGlassMeterValueElement',
        'elementName': 'proto-ui-liquid-glass-meter-value',
      },
    ],
  },
  'liquid-glass-fieldset': {
    'id': 'liquid-glass-fieldset',
    'label': 'LiquidGlass Fieldset (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/fieldset',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'fieldsetRoot',
        'reactExport': 'LiquidGlassFieldsetRoot',
        'vueExport': 'LiquidGlassFieldsetRoot',
        'wcExport': 'LiquidGlassFieldsetRootElement',
        'elementName': 'proto-ui-liquid-glass-fieldset-root',
      },
      {
        'prototypeImport': 'fieldsetLegend',
        'reactExport': 'LiquidGlassFieldsetLegend',
        'vueExport': 'LiquidGlassFieldsetLegend',
        'wcExport': 'LiquidGlassFieldsetLegendElement',
        'elementName': 'proto-ui-liquid-glass-fieldset-legend',
      },
      {
        'prototypeImport': 'fieldsetDescription',
        'reactExport': 'LiquidGlassFieldsetDescription',
        'vueExport': 'LiquidGlassFieldsetDescription',
        'wcExport': 'LiquidGlassFieldsetDescriptionElement',
        'elementName': 'proto-ui-liquid-glass-fieldset-description',
      },
    ],
  },
  'liquid-glass-form': {
    'id': 'liquid-glass-form',
    'label': 'LiquidGlass Form (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/form',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'formRoot',
        'reactExport': 'LiquidGlassFormRoot',
        'vueExport': 'LiquidGlassFormRoot',
        'wcExport': 'LiquidGlassFormRootElement',
        'elementName': 'proto-ui-liquid-glass-form-root',
      },
      {
        'prototypeImport': 'formField',
        'reactExport': 'LiquidGlassFormField',
        'vueExport': 'LiquidGlassFormField',
        'wcExport': 'LiquidGlassFormFieldElement',
        'elementName': 'proto-ui-liquid-glass-form-field',
      },
      {
        'prototypeImport': 'formSubmit',
        'reactExport': 'LiquidGlassFormSubmit',
        'vueExport': 'LiquidGlassFormSubmit',
        'wcExport': 'LiquidGlassFormSubmitElement',
        'elementName': 'proto-ui-liquid-glass-form-submit',
      },
    ],
  },
  'liquid-glass-checkbox-group': {
    'id': 'liquid-glass-checkbox-group',
    'label': 'LiquidGlass CheckboxGroup (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/checkbox-group',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'checkboxGroupRoot',
        'reactExport': 'LiquidGlassCheckboxGroupRoot',
        'vueExport': 'LiquidGlassCheckboxGroupRoot',
        'wcExport': 'LiquidGlassCheckboxGroupRootElement',
        'elementName': 'proto-ui-liquid-glass-checkbox-group-root',
      },
      {
        'prototypeImport': 'checkboxGroupItem',
        'reactExport': 'LiquidGlassCheckboxGroupItem',
        'vueExport': 'LiquidGlassCheckboxGroupItem',
        'wcExport': 'LiquidGlassCheckboxGroupItemElement',
        'elementName': 'proto-ui-liquid-glass-checkbox-group-item',
      },
      {
        'prototypeImport': 'checkboxGroupAll',
        'reactExport': 'LiquidGlassCheckboxGroupAll',
        'vueExport': 'LiquidGlassCheckboxGroupAll',
        'wcExport': 'LiquidGlassCheckboxGroupAllElement',
        'elementName': 'proto-ui-liquid-glass-checkbox-group-all',
      },
    ],
  },
  'base-calendar': {
    'id': 'base-calendar',
    'label': 'Base Calendar (workspace source)',
    'packageName': '@proto.ui/prototypes-base',
    'importPath': '@proto.ui/prototypes-base/calendar',
    'stylePreset': null,
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'calendarRoot',
        'reactExport': 'BaseCalendarRoot',
        'vueExport': 'BaseCalendarRoot',
        'wcExport': 'BaseCalendarRootElement',
        'elementName': 'proto-ui-base-calendar-root',
      },
      {
        'prototypeImport': 'calendarGrid',
        'reactExport': 'BaseCalendarGrid',
        'vueExport': 'BaseCalendarGrid',
        'wcExport': 'BaseCalendarGridElement',
        'elementName': 'proto-ui-base-calendar-grid',
      },
      {
        'prototypeImport': 'calendarRow',
        'reactExport': 'BaseCalendarRow',
        'vueExport': 'BaseCalendarRow',
        'wcExport': 'BaseCalendarRowElement',
        'elementName': 'proto-ui-base-calendar-row',
      },
      {
        'prototypeImport': 'calendarDay',
        'reactExport': 'BaseCalendarDay',
        'vueExport': 'BaseCalendarDay',
        'wcExport': 'BaseCalendarDayElement',
        'elementName': 'proto-ui-base-calendar-day',
      },
      {
        'prototypeImport': 'calendarHeading',
        'reactExport': 'BaseCalendarHeading',
        'vueExport': 'BaseCalendarHeading',
        'wcExport': 'BaseCalendarHeadingElement',
        'elementName': 'proto-ui-base-calendar-heading',
      },
      {
        'prototypeImport': 'calendarPrevious',
        'reactExport': 'BaseCalendarPrevious',
        'vueExport': 'BaseCalendarPrevious',
        'wcExport': 'BaseCalendarPreviousElement',
        'elementName': 'proto-ui-base-calendar-previous',
      },
      {
        'prototypeImport': 'calendarNext',
        'reactExport': 'BaseCalendarNext',
        'vueExport': 'BaseCalendarNext',
        'wcExport': 'BaseCalendarNextElement',
        'elementName': 'proto-ui-base-calendar-next',
      },
    ],
  },
  'shadcn-calendar': {
    'id': 'shadcn-calendar',
    'label': 'Shadcn Calendar (workspace source)',
    'packageName': '@proto.ui/prototypes-shadcn',
    'importPath': '@proto.ui/prototypes-shadcn/calendar',
    'stylePreset': 'shadcn',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'calendarRoot',
        'reactExport': 'ShadcnCalendarRoot',
        'vueExport': 'ShadcnCalendarRoot',
        'wcExport': 'ShadcnCalendarRootElement',
        'elementName': 'proto-ui-shadcn-calendar-root',
      },
      {
        'prototypeImport': 'calendarGrid',
        'reactExport': 'ShadcnCalendarGrid',
        'vueExport': 'ShadcnCalendarGrid',
        'wcExport': 'ShadcnCalendarGridElement',
        'elementName': 'proto-ui-shadcn-calendar-grid',
      },
      {
        'prototypeImport': 'calendarRow',
        'reactExport': 'ShadcnCalendarRow',
        'vueExport': 'ShadcnCalendarRow',
        'wcExport': 'ShadcnCalendarRowElement',
        'elementName': 'proto-ui-shadcn-calendar-row',
      },
      {
        'prototypeImport': 'calendarDay',
        'reactExport': 'ShadcnCalendarDay',
        'vueExport': 'ShadcnCalendarDay',
        'wcExport': 'ShadcnCalendarDayElement',
        'elementName': 'proto-ui-shadcn-calendar-day',
      },
      {
        'prototypeImport': 'calendarHeading',
        'reactExport': 'ShadcnCalendarHeading',
        'vueExport': 'ShadcnCalendarHeading',
        'wcExport': 'ShadcnCalendarHeadingElement',
        'elementName': 'proto-ui-shadcn-calendar-heading',
      },
      {
        'prototypeImport': 'calendarPrevious',
        'reactExport': 'ShadcnCalendarPrevious',
        'vueExport': 'ShadcnCalendarPrevious',
        'wcExport': 'ShadcnCalendarPreviousElement',
        'elementName': 'proto-ui-shadcn-calendar-previous',
      },
      {
        'prototypeImport': 'calendarNext',
        'reactExport': 'ShadcnCalendarNext',
        'vueExport': 'ShadcnCalendarNext',
        'wcExport': 'ShadcnCalendarNextElement',
        'elementName': 'proto-ui-shadcn-calendar-next',
      },
    ],
  },
  'brutalist-calendar': {
    'id': 'brutalist-calendar',
    'label': 'Brutalist Calendar (workspace source)',
    'packageName': '@proto.ui/prototypes-brutalist',
    'importPath': '@proto.ui/prototypes-brutalist/calendar',
    'stylePreset': 'brutalist',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'calendarRoot',
        'reactExport': 'BrutalistCalendarRoot',
        'vueExport': 'BrutalistCalendarRoot',
        'wcExport': 'BrutalistCalendarRootElement',
        'elementName': 'proto-ui-brutalist-calendar-root',
      },
      {
        'prototypeImport': 'calendarGrid',
        'reactExport': 'BrutalistCalendarGrid',
        'vueExport': 'BrutalistCalendarGrid',
        'wcExport': 'BrutalistCalendarGridElement',
        'elementName': 'proto-ui-brutalist-calendar-grid',
      },
      {
        'prototypeImport': 'calendarRow',
        'reactExport': 'BrutalistCalendarRow',
        'vueExport': 'BrutalistCalendarRow',
        'wcExport': 'BrutalistCalendarRowElement',
        'elementName': 'proto-ui-brutalist-calendar-row',
      },
      {
        'prototypeImport': 'calendarDay',
        'reactExport': 'BrutalistCalendarDay',
        'vueExport': 'BrutalistCalendarDay',
        'wcExport': 'BrutalistCalendarDayElement',
        'elementName': 'proto-ui-brutalist-calendar-day',
      },
      {
        'prototypeImport': 'calendarHeading',
        'reactExport': 'BrutalistCalendarHeading',
        'vueExport': 'BrutalistCalendarHeading',
        'wcExport': 'BrutalistCalendarHeadingElement',
        'elementName': 'proto-ui-brutalist-calendar-heading',
      },
      {
        'prototypeImport': 'calendarPrevious',
        'reactExport': 'BrutalistCalendarPrevious',
        'vueExport': 'BrutalistCalendarPrevious',
        'wcExport': 'BrutalistCalendarPreviousElement',
        'elementName': 'proto-ui-brutalist-calendar-previous',
      },
      {
        'prototypeImport': 'calendarNext',
        'reactExport': 'BrutalistCalendarNext',
        'vueExport': 'BrutalistCalendarNext',
        'wcExport': 'BrutalistCalendarNextElement',
        'elementName': 'proto-ui-brutalist-calendar-next',
      },
    ],
  },
  'bootstrap-2-3-2-calendar': {
    'id': 'bootstrap-2-3-2-calendar',
    'label': 'Bootstrap232 Calendar (workspace source)',
    'packageName': '@proto.ui/prototypes-bootstrap-2-3-2',
    'importPath': '@proto.ui/prototypes-bootstrap-2-3-2/calendar',
    'stylePreset': 'bootstrap-2-3-2',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'calendarRoot',
        'reactExport': 'Bootstrap232CalendarRoot',
        'vueExport': 'Bootstrap232CalendarRoot',
        'wcExport': 'Bootstrap232CalendarRootElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-calendar-root',
      },
      {
        'prototypeImport': 'calendarGrid',
        'reactExport': 'Bootstrap232CalendarGrid',
        'vueExport': 'Bootstrap232CalendarGrid',
        'wcExport': 'Bootstrap232CalendarGridElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-calendar-grid',
      },
      {
        'prototypeImport': 'calendarRow',
        'reactExport': 'Bootstrap232CalendarRow',
        'vueExport': 'Bootstrap232CalendarRow',
        'wcExport': 'Bootstrap232CalendarRowElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-calendar-row',
      },
      {
        'prototypeImport': 'calendarDay',
        'reactExport': 'Bootstrap232CalendarDay',
        'vueExport': 'Bootstrap232CalendarDay',
        'wcExport': 'Bootstrap232CalendarDayElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-calendar-day',
      },
      {
        'prototypeImport': 'calendarHeading',
        'reactExport': 'Bootstrap232CalendarHeading',
        'vueExport': 'Bootstrap232CalendarHeading',
        'wcExport': 'Bootstrap232CalendarHeadingElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-calendar-heading',
      },
      {
        'prototypeImport': 'calendarPrevious',
        'reactExport': 'Bootstrap232CalendarPrevious',
        'vueExport': 'Bootstrap232CalendarPrevious',
        'wcExport': 'Bootstrap232CalendarPreviousElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-calendar-previous',
      },
      {
        'prototypeImport': 'calendarNext',
        'reactExport': 'Bootstrap232CalendarNext',
        'vueExport': 'Bootstrap232CalendarNext',
        'wcExport': 'Bootstrap232CalendarNextElement',
        'elementName': 'proto-ui-bootstrap-2-3-2-calendar-next',
      },
    ],
  },
  'liquid-glass-calendar': {
    'id': 'liquid-glass-calendar',
    'label': 'LiquidGlass Calendar (workspace source)',
    'packageName': '@proto.ui/prototypes-liquid-glass',
    'importPath': '@proto.ui/prototypes-liquid-glass/calendar',
    'stylePreset': 'liquid-glass',
    'sourceOnly': true,
    'items': [
      {
        'prototypeImport': 'calendarRoot',
        'reactExport': 'LiquidGlassCalendarRoot',
        'vueExport': 'LiquidGlassCalendarRoot',
        'wcExport': 'LiquidGlassCalendarRootElement',
        'elementName': 'proto-ui-liquid-glass-calendar-root',
      },
      {
        'prototypeImport': 'calendarGrid',
        'reactExport': 'LiquidGlassCalendarGrid',
        'vueExport': 'LiquidGlassCalendarGrid',
        'wcExport': 'LiquidGlassCalendarGridElement',
        'elementName': 'proto-ui-liquid-glass-calendar-grid',
      },
      {
        'prototypeImport': 'calendarRow',
        'reactExport': 'LiquidGlassCalendarRow',
        'vueExport': 'LiquidGlassCalendarRow',
        'wcExport': 'LiquidGlassCalendarRowElement',
        'elementName': 'proto-ui-liquid-glass-calendar-row',
      },
      {
        'prototypeImport': 'calendarDay',
        'reactExport': 'LiquidGlassCalendarDay',
        'vueExport': 'LiquidGlassCalendarDay',
        'wcExport': 'LiquidGlassCalendarDayElement',
        'elementName': 'proto-ui-liquid-glass-calendar-day',
      },
      {
        'prototypeImport': 'calendarHeading',
        'reactExport': 'LiquidGlassCalendarHeading',
        'vueExport': 'LiquidGlassCalendarHeading',
        'wcExport': 'LiquidGlassCalendarHeadingElement',
        'elementName': 'proto-ui-liquid-glass-calendar-heading',
      },
      {
        'prototypeImport': 'calendarPrevious',
        'reactExport': 'LiquidGlassCalendarPrevious',
        'vueExport': 'LiquidGlassCalendarPrevious',
        'wcExport': 'LiquidGlassCalendarPreviousElement',
        'elementName': 'proto-ui-liquid-glass-calendar-previous',
      },
      {
        'prototypeImport': 'calendarNext',
        'reactExport': 'LiquidGlassCalendarNext',
        'vueExport': 'LiquidGlassCalendarNext',
        'wcExport': 'LiquidGlassCalendarNextElement',
        'elementName': 'proto-ui-liquid-glass-calendar-next',
      },
    ],
  },
};
