/* This file is generated by scripts/components/generate-shadcn-component-presets.mjs. */
/* Edit the component-local switch/preset.ts or dialog/preset.ts recipe instead. */

export const SHADCN_COMPONENT_PRESET_RECIPES = {
  'shadcn-switch': {
    'kind': 'replaceable-default-part',
    'placement': 'direct-child',
    'exportName': 'ShadcnSwitch',
    'rootPrototype': 'shadcnSwitchRoot',
    'defaultPartPrototype': 'shadcnSwitchThumb',
    'inputName': 'thumb',
    'elementName': 'proto-ui-shadcn-switch',
    'omissionAttribute': 'data-pui-no-default-thumb',
  },
  'shadcn-dialog': {
    'kind': 'replaceable-default-part',
    'placement': 'direct-child',
    'exportName': 'ShadcnDialogContent',
    'rootPrototype': 'shadcnDialogContent',
    'defaultPartPrototype': 'shadcnDialogCloseIcon',
    'inputName': 'close',
    'elementName': 'proto-ui-shadcn-dialog-content',
    'omissionAttribute': 'data-pui-no-default-close',
  },
  'shadcn-checkbox': {
    'kind': 'replaceable-default-part',
    'placement': 'direct-child',
    'exportName': 'ShadcnCheckbox',
    'rootPrototype': 'shadcnCheckboxRoot',
    'defaultPartPrototype': 'shadcnCheckboxIndicator',
    'inputName': 'indicator',
    'elementName': 'proto-ui-shadcn-checkbox',
    'omissionAttribute': 'data-pui-no-default-indicator',
  },
} as const;
